import { createClient } from '@/lib/supabase/server'

export const dynamic = 'force-dynamic'
type Profile = { id: string; full_name: string | null; email: string | null; phone: string | null }
type Kyc = { user_id: string; status: string | null; verification_type: string | null; provider_customer_ref: string | null; verified_at: string | null }
type Customer = { user_id: string; status: string | null; provider_customer_id: string | null; provider_customer_code: string | null }
const fmt = (v: string | null) => v ? new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(v)) : '—'
const pretty = (v: string) => v.replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, c => c.toUpperCase())
const statusTone = (status: string) => status === 'VERIFIED' ? 'verified' : status === 'PENDING' || status === 'IN_REVIEW' ? 'pending' : status === 'REJECTED' ? 'rejected' : 'neutral'

export default async function AdminKycPage() {
  const supabase = await createClient()
  const [{ data: profiles }, { data: kycs }, { data: customers }] = await Promise.all([
    supabase.from('profiles').select('id,full_name,email,phone').order('full_name'),
    supabase.from('user_kyc_profiles').select('user_id,status,verification_type,provider_customer_ref,verified_at'),
    supabase.from('provider_customers').select('user_id,status,provider_customer_id,provider_customer_code'),
  ])
  const kycMap = new Map((kycs ?? []).map((x: any) => [x.user_id, x as Kyc]))
  const customerMap = new Map((customers ?? []).map((x: any) => [x.user_id, x as Customer]))
  const rows = ((profiles ?? []) as Profile[]).map(u => { const k = kycMap.get(u.id), c = customerMap.get(u.id); const status = String(k?.status ?? c?.status ?? 'NOT_STARTED').toUpperCase(); return { u, k, c, status } })
  const verified = rows.filter(x => x.status === 'VERIFIED').length
  const pending = rows.filter(x => ['PENDING', 'IN_REVIEW'].includes(x.status)).length
  const rejected = rows.filter(x => x.status === 'REJECTED').length
  const outstanding = rows.length - verified
  return <section className="admin-kyc p-4 sm:p-7 lg:p-9 max-w-[1500px] mx-auto">
    <style>{`.kyc-stat{animation:kycIn .55s cubic-bezier(.22,1,.36,1) both}.kyc-delay-0{animation-delay:40ms}.kyc-delay-1{animation-delay:90ms}.kyc-delay-2{animation-delay:140ms}.kyc-delay-3{animation-delay:190ms}.kyc-mobile-row{animation:kycIn .5s cubic-bezier(.22,1,.36,1) both}@keyframes kycIn{from{opacity:0;transform:translateY(12px) scale(.985)}to{opacity:1;transform:translateY(0) scale(1)}}.kyc-badge{display:inline-flex;align-items:center;border-radius:999px;padding:.38rem .7rem;font-size:.68rem;font-weight:800;letter-spacing:.01em;white-space:nowrap}.kyc-verified{color:#087536;background:#eaf9ef;border:1px solid #b9e7c8}.kyc-pending{color:#8a6500;background:#fff8df;border:1px solid #f0d77d}.kyc-rejected{color:#a12626;background:#fff0f0;border:1px solid #efb8b8}.kyc-neutral{color:#53635a;background:#f1f5f2;border:1px solid #d6e1da}.kyc-label{font-size:9px;font-weight:900;letter-spacing:.12em;text-transform:uppercase;color:#526158}.kyc-value{margin-top:.25rem;font-size:.8rem;font-weight:700;color:#17231c;overflow-wrap:anywhere}.admin-kyc{color:#17231c}.admin-kyc tr{transition:background-color .2s ease,transform .2s ease}.admin-kyc tr:hover{transform:translateX(2px)}@media(prefers-reduced-motion:reduce){.kyc-stat,.kyc-mobile-row{animation:none}.admin-kyc tr{transition:none}}html.dark .kyc-verified{color:#86efac;background:#123421;border-color:#2e6b45}html.dark .kyc-pending{color:#f6c85f;background:#3a2d10;border-color:#705b25}html.dark .kyc-rejected{color:#fca5a5;background:#3a1919;border-color:#633030}html.dark .kyc-neutral{color:#b7c7be;background:#182b20;border-color:#294533}html.dark .kyc-label{color:#b8c8be}html.dark .kyc-value{color:#e4ece7}html.dark .admin-kyc{color:#f4f8f5}`}</style>
    <header className="relative overflow-hidden rounded-[28px] border border-[#dce8df] bg-white p-5 sm:p-7 shadow-[0_18px_60px_rgba(12,49,28,.08)] dark:border-[#23442f] dark:bg-[#0d1d13] dark:shadow-[0_18px_70px_rgba(0,0,0,.24)]">
      <div className="pointer-events-none absolute -right-24 -top-24 h-56 w-56 rounded-full bg-[#22c55e]/10 blur-3xl" /><div className="pointer-events-none absolute right-24 bottom-[-70px] h-36 w-36 rounded-full bg-[#86efac]/10 blur-3xl" />
      <div className="relative flex flex-col lg:flex-row lg:items-end lg:justify-between gap-6"><div><div className="flex items-center gap-2 text-[10px] font-black tracking-[.24em] text-[#168447]"><span className="h-1.5 w-1.5 rounded-full bg-[#22c55e] shadow-[0_0_12px_rgba(34,197,94,.8)]"/> COMPLIANCE CONTROL</div><h1 className="mt-3 text-3xl sm:text-4xl font-black tracking-[-.035em] text-[#101812] dark:text-white">Identity verification</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#526158] dark:text-[#c0cec5]">Live customer KYC status, verification method and provider linkage.</p></div><div className="rounded-2xl border border-[#dce8df] bg-[#f6fbf7] px-4 py-3 dark:border-[#23442f] dark:bg-[#102419]"><p className="text-[9px] font-black tracking-[.18em] text-[#5d6b63] dark:text-[#b2c2b8]">SYSTEM SOURCE</p><p className="mt-1 text-sm font-bold text-[#173221] dark:text-[#e8f0eb]">Paystack-backed KYC</p></div></div>
    </header>
    <div className="mt-5 grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{[["TOTAL USERS", rows.length, 'neutral'], ['VERIFIED', verified, 'verified'], ['IN REVIEW', pending, 'pending'], ['OUTSTANDING', outstanding, 'neutral']].map(([label, value, tone], i) => <div key={String(label)} className={`kyc-stat kyc-delay-${i} rounded-2xl border p-4 sm:p-5 ${tone === 'verified' ? 'border-[#b9e7c8] bg-[#effaf2] dark:border-[#2e6b45] dark:bg-[#102d1b]' : 'border-[#dce8df] bg-white dark:border-[#23442f] dark:bg-[#102419]'}`}><div className="flex items-center justify-between"><p className="text-[9px] sm:text-[10px] font-black tracking-[.16em] text-[#526158] dark:text-[#b2c2b8]">{label}</p><span className={`h-2 w-2 rounded-full ${tone === 'verified' ? 'bg-[#22c55e] shadow-[0_0_10px_rgba(34,197,94,.7)]' : tone === 'pending' ? 'bg-[#eab308]' : 'bg-[#8fa196]'}`}/></div><p className="mt-3 text-2xl sm:text-3xl font-black tracking-tight text-[#132019] dark:text-white">{value}</p></div>)}</div>
    <div className="mt-5 rounded-[24px] border border-[#dce8df] bg-white overflow-hidden shadow-[0_14px_45px_rgba(12,49,28,.06)] dark:border-[#23442f] dark:bg-[#0d1d13] dark:shadow-[0_14px_50px_rgba(0,0,0,.2)]"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3 border-b border-[#e6ede8] px-5 py-5 dark:border-[#203b2a]"><div><h2 className="text-base font-black text-[#15231b] dark:text-white">Verification queue</h2><p className="mt-1 text-xs text-[#526158] dark:text-[#b9c8bf]">Review identity state, verification method and provider linkage.</p></div><div className="flex flex-wrap gap-2 text-[10px] font-bold"><span className="rounded-full bg-[#effaf2] px-3 py-1.5 text-[#168447] dark:bg-[#123421] dark:text-[#86efac]">{verified} verified</span><span className="rounded-full bg-[#fff8df] px-3 py-1.5 text-[#936d00] dark:bg-[#3a2d10] dark:text-[#f6c85f]">{pending} in review</span><span className="rounded-full bg-[#f4f6f5] px-3 py-1.5 text-[#59675f] dark:bg-[#182b20] dark:text-[#b7c7be]">{rejected} rejected</span></div></div>
      <div className="hidden md:block overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#f7faf8] text-[#56645b] dark:bg-[#102419] dark:text-[#b5c5bb]"><tr>{['Customer','Status','Verification method','Provider customer','Verified at'].map(h => <th key={h} className="px-5 py-3.5 text-left text-[10px] font-black uppercase tracking-[.1em]">{h}</th>)}</tr></thead><tbody className="divide-y divide-[#edf1ee] dark:divide-[#203b2a]">{rows.map(({u,k,c,status}) => { const tone=statusTone(status); return <tr key={u.id} className="group hover:bg-[#f7fbf8] dark:hover:bg-[#102419]"><td className="px-5 py-4"><p className="font-bold text-[#15231b] dark:text-white">{u.full_name || 'Unnamed user'}</p><p className="mt-0.5 text-xs text-[#66746b] dark:text-[#b1c1b8]">{u.email || u.phone || 'No contact details'}</p></td><td className="px-5 py-4"><span className={`kyc-badge kyc-${tone}`}>{pretty(status)}</span></td><td className="px-5 py-4 text-[#35463c] dark:text-[#d0dbd5]">{k?.verification_type ? pretty(k.verification_type) : 'Not submitted'}</td><td className="px-5 py-4 font-mono text-xs text-[#4e5d55] dark:text-[#c0ccc5]">{k?.provider_customer_ref || c?.provider_customer_code || c?.provider_customer_id || 'Not linked'}</td><td className="px-5 py-4 text-xs text-[#5f6d64] dark:text-[#b4c2ba]">{fmt(k?.verified_at || null)}</td></tr> })}</tbody></table></div>
      <div className="md:hidden divide-y divide-[#edf1ee] dark:divide-[#203b2a]">{rows.map(({u,k,c,status}) => { const tone=statusTone(status); return <article key={u.id} className="kyc-mobile-row p-4 hover:bg-[#f7fbf8] dark:hover:bg-[#102419]"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-bold text-[#15231b] dark:text-white">{u.full_name || 'Unnamed user'}</p><p className="truncate text-xs text-[#66746b] dark:text-[#b1c1b8]">{u.email || u.phone || 'No contact details'}</p></div><span className={`kyc-badge kyc-${tone}`}>{pretty(status)}</span></div><div className="mt-4 grid grid-cols-2 gap-3"><div><p className="kyc-label">Method</p><p className="kyc-value">{k?.verification_type ? pretty(k.verification_type) : 'Not submitted'}</p></div><div><p className="kyc-label">Verified</p><p className="kyc-value">{fmt(k?.verified_at || null)}</p></div><div className="col-span-2"><p className="kyc-label">Provider customer</p><p className="kyc-value font-mono">{k?.provider_customer_ref || c?.provider_customer_code || c?.provider_customer_id || 'Not linked'}</p></div></div></article> })}</div>
      {!rows.length && <div className="px-6 py-16 text-center"><div className="mx-auto h-12 w-12 rounded-2xl bg-[#effaf2] flex items-center justify-center text-[#168447] dark:bg-[#123421]">✓</div><p className="mt-4 font-bold text-[#15231b] dark:text-white">No customer records yet</p><p className="mt-1 text-sm text-[#5d6b63] dark:text-[#b9c8bf]">KYC activity will appear here as users register.</p></div>}
    </div>
  </section>
}