'use client';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';

export default function KycStatusPage() {
  const params = useSearchParams();
  const status = params.get('status') || 'pending';
  const rejected = status === 'rejected';
  const approved = status === 'approved';
  const title = approved ? 'Identity Verified' : rejected ? 'Verification Needs Attention' : 'Verification Under Review';
  const body = approved ? 'Your identity has been verified. Your Alajo account is ready for savings groups.' : rejected ? 'We could not complete your verification. Review your information and submit again.' : 'Your verification details have been received. We are reviewing them before you can join a savings group.';
  return <main className="min-h-screen bg-white grid lg:grid-cols-2">
    <section className="relative hidden lg:block p-10 border-r border-gray-100 overflow-hidden"><div className="relative z-10"><Link href="/" className="text-[22px] font-extrabold tracking-tight text-gray-900">Alajo ◌</Link><h1 className="mt-8 font-bold text-[28px] leading-[1.2] text-gray-900 max-w-[320px]">Smart Rotational Savings for <span className="text-[#16a34a]">Everyone</span></h1><p className="mt-3 text-[15px] text-gray-500 max-w-[300px]">Join thousands of people already saving and growing together with Alajo.</p><div className="mt-8 space-y-5"><Feature icon="✓" title="Secure & Verified" text="Your identity helps keep your account and savings secure."/><Feature icon="👥" title="Trusted Savings" text="Save with a structured group built around clear rules."/><Feature icon="🔒" title="Protected" text="Your account information is handled securely."/></div></div><div className="absolute left-[-40px] bottom-[-40px] w-56 h-56 rounded-full bg-[#eab308]/25"/><div className="absolute left-[-60px] bottom-[-80px] w-64 h-64 rounded-full bg-[#14532d]/90"/></section>
    <section className="p-8 sm:p-12 flex items-center justify-center"><div className="max-w-[420px] w-full text-center"><div className={`w-16 h-16 mx-auto rounded-full flex items-center justify-center text-3xl ${approved ? 'bg-green-50 text-[#16a34a]' : rejected ? 'bg-red-50 text-red-600' : 'bg-yellow-50 text-yellow-600'}`}>{approved ? '✓' : rejected ? '!' : '⏳'}</div><h2 className="mt-5 font-extrabold text-[25px] text-gray-900">{title}</h2><p className="mt-3 text-gray-500 text-[15px] leading-relaxed">{body}</p><div className="mt-6 rounded-md bg-gray-50 border border-gray-100 p-4 text-left"><div className="flex items-center justify-between"><span className="text-sm text-gray-500">KYC status</span><span className="text-sm font-semibold capitalize text-gray-900">{status.replace('_', ' ')}</span></div><div className="mt-3 h-2 rounded-full bg-gray-200 overflow-hidden"><div className={`h-full ${approved ? 'w-full bg-[#16a34a]' : rejected ? 'w-1/3 bg-red-500' : 'w-2/3 bg-[#eab308]'}`} /></div></div><Link href={approved ? '/dashboard' : rejected ? '/kyc/verification' : '/dashboard'} className="mt-6 block w-full py-3 rounded-md bg-[#14532d] text-white font-semibold text-[15px]">{approved ? 'Go to Dashboard' : rejected ? 'Resubmit Verification' : 'Continue to Dashboard'}</Link>{!approved && <p className="mt-4 text-[13px] text-gray-400">You will not be able to join a savings group until required verification is complete.</p>}</div></section>
  </main>;
}
function Feature({ icon, title, text }: { icon: string; title: string; text: string }) { return <div className="flex gap-3"><div className="w-9 h-9 shrink-0 rounded-full bg-green-50 flex items-center justify-center text-[#16a34a]">{icon}</div><div><p className="font-semibold text-[14px] text-gray-900">{title}</p><p className="text-[13px] text-gray-500">{text}</p></div></div>; }
