'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { AlajoIcon } from '@/components/ui/alajo-icon'

type IconName = 'wallet' | 'clock' | 'payouts' | 'check'
type Row = { id:string; amount:number; due_date:string; status:string; outstanding_amount:number; group:{name:string; contribution_amount:number; cycle:string}|null }
const money=(n:number)=>`₦${Number(n||0).toLocaleString('en-NG',{minimumFractionDigits:2})}`
const nav=[['dashboard','/dashboard','Dashboard'],['groups','/groups','Groups'],['contributions','/contributions','Contributions'],['payouts','/payouts','Payouts'],['wallet','/wallet','Wallet'],['transactions','/transactions','Transactions'],['invite','/invite-earn','Invite & Earn'],['notifications','/notifications','Notifications'],['settings','/settings','Settings'],['help','/help-center','Help Center'],['logout','/login','Logout']] as const

export default function ContributionsPage(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState<'all'|'completed'|'upcoming'|'missed'>('all'),[name,setName]=useState('User')
 useEffect(()=>{let dead=false;async function load(){try{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login';return}const {data:schedules,error:scheduleError}=await supabase.from('contribution_schedules').select('id,amount,due_date,status,outstanding_amount').order('due_date',{ascending:false});if(scheduleError)throw scheduleError;if(!dead)setRows((schedules||[]).map((s:any)=>({...s,group:null})) as Row[])}catch(e){if(!dead)setError(e instanceof Error?e.message:'Unable to load contributions.')}finally{if(!dead)setLoading(false)}}load();fetch('/api/auth/session',{cache:'no-store'}).then(async r=>r.ok?r.json():null).then(d=>{if(!dead&&d?.name)setName(d.name)}).catch(()=>{});return()=>{dead=true}},[])
 const completed=rows.filter(r=>r.status==='paid'),missed=rows.filter(r=>['overdue','missed'].includes(r.status)),upcoming=rows.filter(r=>['pending','processing'].includes(r.status)),visible=tab==='completed'?completed:tab==='upcoming'?upcoming:tab==='missed'?missed:rows
 const total=rows.reduce((s,r)=>s+Number(r.amount||0),0),paid=completed.reduce((s,r)=>s+Number(r.amount||0),0),upcomingTotal=upcoming.reduce((s,r)=>s+Number(r.amount||0),0),missedTotal=missed.reduce((s,r)=>s+Number(r.amount||0),0),next=upcoming[0],progress=total?Math.min(100,Math.round(paid/total*100)):0
 const label=(s:string)=>s==='paid'?'Completed':['overdue','missed'].includes(s)?'Missed':s==='processing'?'Processing':'Upcoming'
 const statusClass=(s:string)=>s==='paid'?'bg-green-50 text-[#16a34a]':['overdue','missed'].includes(s)?'bg-red-50 text-red-500':'bg-blue-50 text-blue-500'
 return <div className="min-h-screen bg-[#f8faf9] text-gray-900 flex">
  <aside className="hidden lg:flex w-[250px] shrink-0 min-h-screen bg-[#0b2313] text-white p-5 flex-col fixed inset-y-0 left-0">
   <Link href="/dashboard" className="px-2 text-[26px] font-extrabold tracking-tight flex items-center gap-2">Alajo <span className="text-yellow-400"><AlajoIcon name="coin" size={20}/></span></Link>
   <nav className="mt-8 flex-1 space-y-1 text-[14px] font-medium">{nav.map(([icon,href,label])=><Link key={label} href={href} className={`flex items-center gap-3 px-3 py-2.5 rounded-lg ${label==='Contributions'?'bg-white/10 text-white':'text-gray-300 hover:bg-white/5'}`}><AlajoIcon name={icon} size={18}/><span>{label}</span>{label==='Notifications'&&<span className="ml-auto w-1.5 h-1.5 rounded-full bg-[#eab308]"/>}</Link>)}</nav>
   <div className="bg-[#123524] rounded-xl p-4 text-white"><p className="font-semibold text-[14px]">Stay consistent, grow together</p><p className="text-[12px] text-gray-300 mt-1">Make your contributions on time and reach your goals faster.</p><Link href="#contributions" className="mt-3 inline-block bg-white text-[#0b2313] text-[13px] font-semibold px-3 py-1.5 rounded-md">Make Contribution →</Link><div className="absolute bottom-5 right-7 text-yellow-300"><AlajoIcon name="coin" size={27}/></div></div>
  </aside>
  <main className="lg:ml-[250px] flex-1 min-w-0">
   <header className="h-[76px] bg-white border-b border-gray-100 px-5 sm:px-8 flex items-center justify-between"><div><p className="text-gray-400 text-[13px]">Contributions</p><h1 className="font-semibold text-[18px]">My Contributions</h1></div><div className="flex items-center gap-4"><AlajoIcon name="notifications" size={19}/><div className="w-9 h-9 rounded-full bg-gray-200 flex items-center justify-center font-semibold">{name.charAt(0).toUpperCase()}</div></div></header>
   <section className="p-5 sm:p-8 max-w-[1250px]">
    <p className="text-gray-500 text-[14px]">Track your contributions, upcoming payments and savings progress.</p>
    {error&&<div className="mt-5 rounded-xl bg-red-50 text-red-700 p-4 text-sm">{error}</div>}
    {loading?<div className="mt-6 bg-white rounded-xl border border-gray-100 p-10 text-center text-gray-500">Loading contributions…</div>:<>
     <div className="mt-6 grid grid-cols-2 xl:grid-cols-4 gap-5"><Stat icon="wallet" bg="bg-green-50" color="text-[#16a34a]" title="Total Contributions" value={money(total)} sub="Across all groups"/><Stat icon="clock" bg="bg-blue-50" color="text-blue-500" title="This Month" value={money(rows.filter(r=>new Date(r.due_date).getMonth()===new Date().getMonth()).reduce((s,r)=>s+Number(r.amount||0),0))} sub={new Date().toLocaleDateString('en-NG',{month:'long',year:'numeric'})}/><Stat icon="payouts" bg="bg-orange-50" color="text-orange-500" title="Upcoming" value={money(upcomingTotal)} sub="Due in the next 7 days"/><Stat icon="check" bg="bg-purple-50" color="text-purple-500" title="Completed" value={money(paid)} sub="Total completed"/></div>
     <div className="mt-6 grid grid-cols-1 xl:grid-cols-3 gap-5">
      <div id="contributions" className="xl:col-span-2 bg-white rounded-xl border border-gray-100 p-5"><div className="flex items-center gap-6 text-[14px] font-medium border-b border-gray-100 pb-3 overflow-x-auto">{([['all','All Contributions'],['completed','Completed'],['upcoming','Upcoming'],['missed','Missed']] as const).map(([k,v])=><button key={k} onClick={()=>setTab(k)} className={tab===k?'text-[#16a34a] border-b-2 border-[#16a34a] pb-3 -mb-3 whitespace-nowrap':'text-gray-400 whitespace-nowrap pb-3 -mb-3'}>{v}</button>)}</div><div className="mt-4 space-y-1">{visible.length?visible.map(r=><div key={r.id} className="flex items-center justify-between gap-4 py-3 border-b border-gray-50 last:border-0"><div className="flex items-center gap-3 min-w-0"><div className={`w-9 h-9 rounded-full flex items-center justify-center shrink-0 ${r.status==='paid'?'bg-green-50 text-[#16a34a}':['overdue','missed'].includes(r.status)?'bg-red-50 text-red-500':'bg-blue-50 text-blue-500'}`}><AlajoIcon name={r.status==='paid'?'check':['overdue','missed'].includes(r.status)?'info':'clock'} size={17}/></div><div className="min-w-0"><p className="font-medium truncate">{money(r.amount)} Contribution</p><p className="text-gray-400 text-[12px]">{r.group?.name||'Savings Group'} • {r.group?.cycle||'6 Months Cycle'}<br/>{new Date(r.due_date).toLocaleDateString('en-NG',{day:'numeric',month:'short',year:'numeric'})}</p></div></div><span className={`font-medium text-[12px] rounded px-2 py-0.5 shrink-0 ${statusClass(r.status)}`}>{label(r.status)}</span><span className="font-semibold shrink-0">{money(r.amount)}</span></div>):<div className="py-12 text-center"><p className="font-medium text-gray-700">No contributions yet</p><p className="text-sm text-gray-400 mt-1">Your admin-created contribution schedules will appear here.</p></div>}</div></div>
      <div className="space-y-5"><div className="bg-white rounded-xl border border-gray-100 p-5"><h3 className="font-semibold">Contribution Summary</h3><div className="mt-4 flex items-center gap-4"><div className="relative w-20 h-20"><svg viewBox="0 0 36 36" className="w-20 h-20 -rotate-90"><circle cx="18" cy="18" r="16" fill="none" stroke="#e5e7eb" strokeWidth="3"/><circle cx="18" cy="18" r="16" fill="none" stroke="#16a34a" strokeWidth="3" strokeDasharray={`${progress},100`}/></svg><span className="absolute inset-0 flex items-center justify-center text-[16px] font-bold">{progress}%</span></div><div className="text-[13px] space-y-1"><p><span className="text-[#16a34a]">●</span> Completed <b>{money(paid)}</b></p><p><span className="text-blue-500">●</span> Upcoming <b>{money(upcomingTotal)}</b></p><p><span className="text-red-500">●</span> Missed <b>{money(missedTotal)}</b></p></div></div></div>
       <div className="bg-white rounded-xl border border-gray-100 p-5"><h3 className="font-semibold">Next Contribution</h3>{next?<><div className="mt-3 flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-blue-50 flex items-center justify-center text-blue-500"><AlajoIcon name="clock"/></div><div><p className="font-semibold text-[14px]">{next.group?.name||'Savings Group'}</p><p className="text-[12px] text-gray-400">Amount</p><p className="text-[13px] font-semibold">{money(next.amount)}</p><p className="text-[12px] text-gray-400 mt-1">Due Date</p><p className="text-[13px] font-semibold text-blue-500">{new Date(next.due_date).toLocaleDateString('en-NG',{day:'numeric',month:'short',year:'numeric'})}</p></div></div><Link href={`/contributions/make?id=${next.id}`} className="mt-4 block text-center bg-blue-500 text-white font-semibold text-[14px] py-2.5 rounded-md">Make Contribution</Link></>:<p className="mt-3 text-sm text-gray-400">No upcoming contribution.</p>}</div>
       <div className="bg-white rounded-xl border border-gray-100 p-5"><h3 className="font-semibold">Quick Actions</h3><div className="mt-3 space-y-3 text-[14px] text-gray-700"><Link href="/transactions" className="flex justify-between items-center">Contribution History <span className="text-gray-300">›</span></Link><Link href="/wallet" className="flex justify-between items-center">Payment Methods <span className="text-gray-300">›</span></Link><Link href="/settings" className="flex justify-between items-center">Auto Contribution <span className="text-[#16a34a] text-[12px] bg-green-50 rounded px-2 py-0.5">Settings</span></Link></div></div></div>
     </div>
    </>}
   </section>
  </main>
 </div>
}

function Stat({icon,bg,color,title,value,sub}:{icon:IconName;bg:string;color:string;title:string;value:string;sub:string}){return <div className="bg-white rounded-xl border border-gray-100 p-5"><div className={`w-9 h-9 rounded-full ${bg} flex items-center justify-center ${color}`}><AlajoIcon name={icon} size={18}/></div><p className="mt-3 text-gray-500 text-[13px]">{title}</p><p className="text-[20px] font-bold text-gray-900">{value}</p><p className="text-[12px] text-gray-400 mt-1">{sub}</p></div>}
