'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

const roles = ['admin','finance_admin','kyc_admin','support_admin'] as const
type AdminRow={id:string;full_name:string|null;email:string|null;status:string|null;role:string|null}

export default function AdministratorsPage(){
 const supabase=createClient();const [admins,setAdmins]=useState<AdminRow[]>([]);const [email,setEmail]=useState('');const [role,setRole]=useState<(typeof roles)[number]>('admin');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('')
 async function load(){setLoading(true);setError('');const {data,error}=await supabase.from('user_roles').select('user_id,role,profiles!inner(id,full_name,email,status)').order('created_at',{ascending:true});if(error)setError(error.message);else setAdmins((data||[]).map((r:any)=>({id:r.user_id,role:r.role,...r.profiles})));setLoading(false)}
 useEffect(()=>{load()},[])
 async function addAdmin(){setSaving(true);setError('');setMessage('');try{const {data:existing,error:findError}=await supabase.rpc('admin_find_user_by_email',{p_email:email.trim()});if(findError)throw findError;const target=existing?.[0];if(target){const {error:roleError}=await supabase.rpc('admin_set_user_role',{p_user_id:target.id,p_role:role});if(roleError)throw roleError;setMessage(`${target.email} now has ${role.replaceAll('_',' ')} access.`)}else{const {data,error:inviteError}=await supabase.functions.invoke('admin-invite',{body:{email:email.trim(),role}});if(inviteError)throw inviteError;if(error)throw new Error(error);setMessage(`Administrator invitation sent to ${email.trim()}.`)}setEmail('');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create administrator access.')}finally{setSaving(false)}}
 async function changeRole(id:string,next:string){setError('');const {error}=await supabase.rpc('admin_set_user_role',{p_user_id:id,p_role:next});if(error)setError(error.message);else await load()}
 async function removeAdmin(id:string){if(!confirm('Remove administrator access from this user? Their Deotech Finance account and financial history will remain intact.'))return;const {error}=await supabase.rpc('admin_remove_user_role',{p_user_id:id});if(error)setError(error.message);else await load()}
 return <main className="min-h-screen bg-[#06130b] text-white p-5 sm:p-8"><div className="max-w-6xl mx-auto"><p className="text-[10px] uppercase tracking-[.22em] font-bold text-[#16a34a]">Administration</p><h1 className="text-3xl font-black mt-1">Administrators</h1><p className="text-sm text-gray-300 mt-2">Create, invite and manage administrator access.</p>{error&&<div className="mt-4 rounded-xl border border-red-300/30 bg-red-500/10 p-3 text-sm text-red-200">{error}</div>}{message&&<div className="mt-4 rounded-xl border border-[#16a34a]/30 bg-[#16a34a]/10 p-3 text-sm text-[#86efac]">{message}</div>}
 <section className="mt-6 rounded-2xl border border-white/10 bg-[#0b2113] p-5"><h2 className="font-bold">Create administrator</h2><p className="text-xs text-gray-400 mt-1">If the email already belongs to a Deotech Finance user, their role is updated immediately. Otherwise an invitation is sent. Super Admin access is reserved and cannot be assigned here.</p><div className="mt-4 flex flex-col sm:flex-row gap-3"><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="user@example.com" type="email" className="flex-1 rounded-xl border border-white/15 bg-white/[.06] px-3 py-2.5 text-sm text-white outline-none focus:border-[#16a34a]"/><select value={role} onChange={e=>setRole(e.target.value as any)} className="rounded-xl border border-white/15 bg-[#102719] px-3 py-2.5 text-sm text-white">{roles.map(r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select><button disabled={!email.trim()||saving} onClick={addAdmin} className="rounded-xl bg-[#16a34a] px-5 py-2.5 text-sm font-bold disabled:opacity-50">{saving?'Creating…':'Create admin'}</button></div></section>
 <section className="mt-5 rounded-2xl border border-white/10 bg-[#0b2113] overflow-hidden"><div className="px-5 py-4 border-b border-white/10"><h2 className="font-bold">Current administrators</h2></div>{loading?<div className="p-8 text-sm text-gray-400">Loading…</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#102719] text-gray-400"><tr><th className="text-left px-5 py-3">Administrator</th><th className="text-left px-5 py-3">Role</th><th className="text-left px-5 py-3">Account</th><th className="text-right px-5 py-3">Actions</th></tr></thead><tbody className="divide-y divide-white/10">{admins.map(a=><tr key={a.id}><td className="px-5 py-4"><p className="font-semibold">{a.full_name||'Unnamed user'}</p><p className="text-xs text-gray-400 mt-0.5">{a.email||'—'}</p></td><td className="px-5 py-4">{a.role==='super_admin'?<span className="text-[#86efac] font-bold">Super Admin</span>:<select value={a.role||'admin'} onChange={e=>changeRole(a.id,e.target.value)} className="rounded-lg border border-white/10 bg-[#102719] px-2 py-1.5 text-xs text-white">{roles.map(r=><option key={r}>{r}</option>)}</select>}</td><td className="px-5 py-4"><span className={a.status==='suspended'?'text-red-300':'text-[#86efac]'}>{a.status==='suspended'?'Disabled':'Active'}</span></td><td className="px-5 py-4 text-right">{a.role!=='super_admin'&&<button onClick={()=>removeAdmin(a.id)} className="text-xs font-bold text-red-300 hover:text-red-200">Remove access</button>}</td></tr>)}</tbody></table></div>}</section></div></main>
}
