'use client'
import { useEffect, useState } from 'react'

type Setting={key:string;boolean_value:boolean|null}
type Item=[string,string,string]
const groups:{title:string;items:Item[]}[]=[
 {title:'Markets & access',items:[['market_registration_enabled','User registration','Allow new users to register.'],['new_accounts_enabled','New accounts','Allow account creation after registration.'],['country_maintenance_mode_enabled','Country maintenance mode','Temporarily restrict a market without disabling ZeePay globally.'],['wallet_enabled','Wallet','Allow wallet operations.'],['savings_enabled','Savings','Enable savings products.'],['deposits_enabled','Deposits','Allow wallet funding/deposits.'],['withdrawals_enabled','Withdrawals','Allow user withdrawals.'],['transfers_enabled','Transfers','Allow internal/external transfers.'],['global_transaction_pause','Global transaction pause','Emergency stop for financial transactions.']]},
 {title:'Payments & settlement',items:[['card_payments_enabled','Card payments','Allow card payment channels where the selected provider supports them.'],['bank_transfer_payments_enabled','Bank transfer payments','Allow bank-transfer funding.'],['ussd_payments_enabled','USSD payments','Allow USSD payment channels where supported.'],['mobile_money_payments_enabled','Mobile Money','Allow mobile-money channels where supported.'],['recurring_payments_enabled','Recurring payments','Allow recurring/automatic payment mandates where supported.'],['payment_retry_enabled','Payment retry','Retry recoverable payment failures.'],['webhook_processing_enabled','Webhook processing','Process provider webhooks.'],['failed_webhook_retry_enabled','Failed webhook retry','Retry recoverable webhook processing failures.'],['automatic_settlement_enabled','Automatic settlement','Automatically settle eligible transactions.'],['automatic_refund_processing_enabled','Automatic refunds','Process eligible refunds automatically.'],['chargeback_handling_enabled','Chargeback handling','Enable automated chargeback workflow.'],['automatic_reconciliation_enabled','Automatic reconciliation','Run transaction reconciliation automatically.']]},
 {title:'Savings automation',items:[['automatic_group_formation_enabled','Automatic group formation','Form eligible savings groups automatically.'],['automatic_contribution_collection_enabled','Automatic contribution collection','Attempt scheduled collections automatically.'],['contribution_reminders_enabled','Contribution reminders','Send contribution reminders.'],['automatic_late_fee_enabled','Automatic late fees','Apply configured late fees automatically.'],['missed_contribution_processing_enabled','Missed contribution processing','Process overdue contribution cases automatically.'],['automatic_cycle_processing_enabled','Automatic cycle processing','Advance and close eligible cycles automatically.'],['automatic_payout_processing_enabled','Automatic payout processing','Process eligible payouts automatically.'],['early_withdrawal_enabled','Early withdrawal','Allow the configured early-withdrawal workflow.']]},
 {title:'KYC & compliance',items:[['kyc_required_enabled','KYC required','Require identity verification.'],['identity_verification_enabled','Identity verification','Enable the configured identity-verification flow.'],['document_verification_enabled','Document verification','Enable document checks where the provider supports them.'],['kyc_manual_review_enabled','Manual KYC review','Allow compliance review for exceptions.'],['manual_compliance_review_enabled','Manual compliance review','Allow compliance teams to hold cases for review.'],['kyc_reverification_enabled','KYC re-verification','Allow scheduled re-verification.'],['enhanced_kyc_enabled','Enhanced KYC','Enable enhanced verification for eligible cases.'],['automatic_kYC_retry_enabled','KYC retry','Retry recoverable provider verification failures.']]},
 {title:'Risk & account protection',items:[['risk_screening_enabled','Risk screening','Run automated risk screening.'],['transaction_monitoring_enabled','Transaction monitoring','Monitor transaction activity.'],['automatic_transaction_risk_review_enabled','Automatic transaction review','Route risk-triggered transactions for review.'],['large_transaction_review_enabled','Large transaction review','Review transactions above configured thresholds.'],['suspicious_activity_review_enabled','Suspicious activity review','Route suspicious activity to compliance review.'],['automatic_account_freeze_enabled','Automatic account freeze','Freeze accounts when configured risk rules trigger.'],['withdrawal_risk_checks_enabled','Withdrawal risk checks','Run risk checks before eligible withdrawals.'],['wallet_freeze_enabled','Wallet freeze control','Allow authorized account-level wallet freezes.']]},
 {title:'Notifications',items:[['email_notifications_enabled','Email notifications','Send transactional email.'],['sms_notifications_enabled','SMS notifications','Send transactional SMS.'],['push_notifications_enabled','Push notifications','Send push notifications.'],['notification_payment_enabled','Payment notifications','Notify users about payment events.'],['notification_kyc_enabled','KYC notifications','Notify users about verification events.'],['notification_savings_enabled','Savings notifications','Notify users about savings events.'],['notification_contribution_enabled','Contribution notifications','Notify users about contribution events.'],['notification_failed_payment_enabled','Failed-payment alerts','Notify users about failed payments.'],['notification_withdrawal_enabled','Withdrawal notifications','Notify users about withdrawals.'],['notification_security_enabled','Security alerts','Send security-related alerts.'],['marketing_notifications_enabled','Marketing notifications','Allow marketing communications.']]},
 {title:'Provider & system health',items:[['provider_health_checks_enabled','Provider health checks','Monitor configured provider availability.'],['dormant_account_checks_enabled','Dormant-account checks','Run scheduled dormant-account checks.'],['savings_account_control_enabled','Savings account control','Allow the savings account-control workflow.']]}
]
export default function OperationalControls(){
 const [values,setValues]=useState<Record<string,boolean>>({}),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState('')
 useEffect(()=>{fetch('/api/admin/settings',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.error)throw Error(d.error);const x:Record<string,boolean>={};(d.settings||[]).forEach((s:Setting)=>{if(s.boolean_value!==null)x[s.key]=s.boolean_value});setValues(x)}).catch(e=>setErr(e.message))},[])
 function toggle(k:string){setValues(v=>({...v,[k]:!v[k]}));setMsg('');setErr('')}
 async function save(){setSaving(true);setErr('');setMsg('');try{const body:Record<string,boolean>={};groups.flatMap(g=>g.items).forEach(([k])=>body[k]=!!values[k]);const r=await fetch('/api/admin/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);setMsg(`Operational controls saved${d.changed!==undefined?` · ${d.changed} settings updated`:''}.`)}catch(e){setErr(e instanceof Error?e.message:'Unable to save controls.')}finally{setSaving(false)}}
 return <main className="min-h-screen bg-[#06130b] text-white px-5 py-7 sm:px-8"><div className="max-w-[1180px] mx-auto"><header className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.22em] font-black text-[#86efac]">ZeePay / Operations</p><h1 className="text-3xl sm:text-4xl font-black mt-1">Operational Controls</h1><p className="text-sm text-[#c7d8cc] mt-2">Control supported operating behaviour without changing code or redeploying.</p></div><button onClick={save} disabled={saving} className="rounded-xl bg-[#16a34a] px-5 py-2.5 text-sm font-black disabled:opacity-50">{saving?'Saving…':'✓ Save controls'}</button></header>{err&&<div className="mt-4 rounded-xl border border-red-400/30 bg-red-500/10 p-3 text-red-100">{err}</div>}{msg&&<div className="mt-4 rounded-xl border border-[#4ade80]/30 bg-[#16a34a]/10 p-3 text-[#d1fae5]">{msg}</div>}<div className="mt-6 grid gap-5 lg:grid-cols-2">{groups.map(g=><section key={g.title} className="rounded-3xl border border-[#1c5130] bg-[#0b2113] p-5 sm:p-6"><h2 className="text-lg font-black">{g.title}</h2><div className="mt-3">{g.items.map(([k,l,d])=><div key={k} className="flex items-center justify-between gap-4 py-4 border-b border-white/10 last:border-0"><div><p className="text-sm font-bold">{l}</p><p className="text-[11px] text-[#c7d8cc] mt-1">{d}</p></div><button type="button" onClick={()=>toggle(k)} aria-pressed={!!values[k]} aria-label={l} className={`h-7 w-12 shrink-0 rounded-full border p-0.5 transition-colors ${values[k]?'bg-[#16a34a] border-[#4ade80]':'bg-white/10 border-white/20'}`}><span className={`block h-6 w-6 rounded-full bg-white transition-transform ${values[k]?'translate-x-5':''}`}/></button></div>)}</div></section>)}</div><p className="mt-5 text-xs text-[#91a49a]">Provider credentials and provider-specific routing remain in the Provider Administration area. These switches configure safe operational behaviour already supported by the backend.</p></div></main>
}
