'use client'
import { useEffect, useState } from 'react'

type Setting={key:string;boolean_value:boolean|null}
const groups=[
 {title:'Market & money movement',items:[['market_registration_enabled','User registration','Allow new users to register.'],['wallet_enabled','Wallet','Allow wallet operations.'],['savings_enabled','Savings','Enable savings products.'],['deposits_enabled','Deposits','Allow wallet funding/deposits.'],['withdrawals_enabled','Withdrawals','Allow user withdrawals.'],['transfers_enabled','Transfers','Allow internal/external transfers.'],['global_transaction_pause','Global transaction pause','Emergency stop for financial transactions.']]},
 {title:'Payments & reconciliation',items:[['payment_retry_enabled','Payment retry','Retry recoverable payment failures.'],['webhook_processing_enabled','Webhook processing','Process provider webhooks.'],['automatic_reconciliation_enabled','Automatic reconciliation','Run transaction reconciliation automatically.']]},
 {title:'Savings automation',items:[['automatic_group_formation_enabled','Automatic group formation','Form eligible savings groups automatically.'],['automatic_contribution_collection_enabled','Automatic contribution collection','Attempt scheduled collections automatically.'],['contribution_reminders_enabled','Contribution reminders','Send contribution reminders.'],['automatic_late_fee_enabled','Automatic late fees','Apply configured late fees automatically.'],['automatic_cycle_processing_enabled','Automatic cycle processing','Advance and close eligible cycles automatically.'],['automatic_payout_processing_enabled','Automatic payout processing','Process eligible payouts automatically.']]},
 {title:'KYC & risk',items:[['kyc_required_enabled','KYC required','Require identity verification.'],['kyc_manual_review_enabled','Manual KYC review','Allow compliance review for exceptions.'],['kyc_reverification_enabled','KYC re-verification','Allow scheduled re-verification.'],['risk_screening_enabled','Risk screening','Run automated risk screening.'],['transaction_monitoring_enabled','Transaction monitoring','Monitor transaction activity.'],['automatic_account_freeze_enabled','Automatic account freeze','Freeze accounts when configured risk rules trigger.']]},
 {title:'Notifications',items:[['email_notifications_enabled','Email notifications','Send transactional email.'],['sms_notifications_enabled','SMS notifications','Send transactional SMS.'],['push_notifications_enabled','Push notifications','Send push notifications.']]}
]
export default function OperationalControls(){
 const [values,setValues]=useState<Record<string,boolean>>({}),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState('')
 useEffect(()=>{fetch('/api/admin/settings',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.error)throw Error(d.error);const x:Record<string,boolean>={};(d.settings||[] as Setting[]).forEach((s:Setting)=>{if(s.boolean_value!==null)x[s.key]=s.boolean_value});setValues(x)}).catch(e=>setErr(e.message))},[])
 function toggle(k:string){setValues(v=>({...v,[k]:!v[k]}));setMsg('');setErr('')}
 async function save(){setSaving(true);setErr('');setMsg('');try{const body:Record<string,boolean>={};groups.flatMap(g=>g.items).forEach(([k])=>body[k]=!!values[k]);const r=await fetch('/api/admin/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);setMsg('Operational controls saved.')}catch(e){setErr(e instanceof Error?e.message:'Unable to save controls.')}finally{setSaving(false)}}
 return <main className="min-h-screen bg-[#06130b] text-white px-5 py-7 sm:px-8"><div className="max-w-[1180px] mx-auto"><header className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.22em] font-black text-[#86efac]">ZeePay / Operations</p><h1 className="text-3xl sm:text-4xl font-black mt-1">Operational Controls</h1><p className="text-sm text-[#c7d8cc] mt-2">Switch normal operating behaviour without changing code or redeploying.</p></div><button onClick={save} disabled={saving} className="rounded-xl bg-[#16a34a] px-5 py-2.5 text-sm font-black disabled:opacity-50">{saving?'Saving…':'✓ Save controls'}</button></header>{err&&<div className="mt-4 rounded-xl border border-red-400/30 bg-red-500/10 p-3 text-red-100">{err}</div>}{msg&&<div className="mt-4 rounded-xl border border-[#4ade80]/30 bg-[#16a34a]/10 p-3 text-[#d1fae5]">{msg}</div>}<div className="mt-6 grid gap-5 lg:grid-cols-2">{groups.map(g=><section key={g.title} className="rounded-3xl border border-[#1c5130] bg-[#0b2113] p-5 sm:p-6"><h2 className="text-lg font-black">{g.title}</h2><div className="mt-3">{g.items.map(([k,l,d])=><div key={k} className="flex items-center justify-between gap-4 py-4 border-b border-white/10 last:border-0"><div><p className="text-sm font-bold">{l}</p><p className="text-[11px] text-[#c7d8cc] mt-1">{d}</p></div><button type="button" onClick={()=>toggle(k)} aria-label={l} className={`h-7 w-12 shrink-0 rounded-full border p-0.5 ${values[k]?'bg-[#16a34a] border-[#4ade80]':'bg-white/10 border-white/20'}`}><span className={`block h-6 w-6 rounded-full bg-white transition-transform ${values[k]?'translate-x-5':''}`}/></button></div>)}</div></section>)}</div><p className="mt-5 text-xs text-[#91a49a]">Provider-specific routing remains in Administration. These switches only control safe operational behaviour already supported by the backend.</p></div></main>
}
