import { useEffect, useMemo, useState } from 'react'
import { SafeAreaView, View, Text, TextInput, Pressable, StyleSheet, ScrollView, ActivityIndicator } from 'react-native'
import { getBanks, getPayouts, requestPayout, verifyPayoutAccount } from '../lib/api'
import { router } from 'expo-router'

export default function Withdrawal() {
  const [banks,setBanks]=useState<any[]>([]); const [bankCode,setBankCode]=useState(''); const [accountNumber,setAccountNumber]=useState(''); const [accountName,setAccountName]=useState(''); const [amount,setAmount]=useState(''); const [payoutId,setPayoutId]=useState<string|undefined>(); const [checking,setChecking]=useState(false); const [submitting,setSubmitting]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('')
  useEffect(()=>{getBanks().then(r=>setBanks(r.banks??[])).catch(()=>setError('Unable to load banks.'));getPayouts().then((r:any)=>{const due=(r.payouts??r.data??[]).find((x:any)=>['DUE','AVAILABLE'].includes(String(x.status??'').toUpperCase()));if(due){setPayoutId(due.id);if(!amount)setAmount(String(due.amount??due.expected_amount??''))}}).catch(()=>{})},[])
  const bank = useMemo(()=>banks.find((b:any)=>String(b.code)===bankCode),[banks,bankCode])
  async function verify(){setError('');setMessage('');if(!bankCode||!/^[0-9]{10}$/.test(accountNumber))return setError('Choose a bank and enter a valid 10-digit account number.');setChecking(true);try{const r:any=await verifyPayoutAccount(accountNumber,bankCode);setAccountName(r.accountName??'');setMessage('Account verified.');}catch(e:any){setAccountName('');setError(e.message||'Unable to verify this account.')}finally{setChecking(false)}}
  async function withdraw(){setError('');setMessage('');const value=Number(amount);if(!accountName||!bankCode||!/^[0-9]{10}$/.test(accountNumber)||!Number.isFinite(value)||value<=0)return setError('Complete account verification and enter a valid amount.');setSubmitting(true);try{const r:any=await requestPayout({amount:value,bankCode,accountNumber,accountName,payoutId,idempotencyKey:`mobile-${Date.now()}-${Math.random().toString(36).slice(2)}`});setMessage(r.status==='PROCESSING'?'Withdrawal submitted. Transfer is processing.':'Withdrawal request submitted.')}catch(e:any){setError(e.message||'Unable to process withdrawal.')}finally{setSubmitting(false)}}
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.brand}>ZeePay</Text><Text style={s.eyebrow}>WITHDRAWAL</Text><Text style={s.title}>Request payout</Text><Text style={s.copy}>Enter your destination account, verify it, then submit your withdrawal.</Text><View style={s.card}><Text style={s.label}>Bank</Text><TextInput value={bankCode} onChangeText={setBankCode} placeholder="Bank code" keyboardType="number-pad" style={s.input}/><Text style={s.hint}>{bank?.name??'Select your bank code from the bank directory.'}</Text><Text style={s.label}>Account number</Text><TextInput value={accountNumber} onChangeText={v=>setAccountNumber(v.replace(/\D/g,''))} placeholder="10-digit account number" keyboardType="number-pad" maxLength={10} style={s.input}/><Pressable onPress={verify} disabled={checking} style={s.secondary}><Text style={s.secondaryText}>{checking?'Verifying account…':'Verify account'}</Text></Pressable>{accountName?<View style={s.verified}><Text style={s.verifiedTitle}>✓ Account verified</Text><Text style={s.verifiedName}>{accountName}</Text></View>:null}<Text style={s.label}>Amount (NGN)</Text><TextInput value={amount} onChangeText={setAmount} placeholder="0.00" keyboardType="decimal-pad" style={s.input}/>{error?<Text style={s.error}>{error}</Text>:null}{message?<Text style={s.success}>{message}</Text>:null}<Pressable onPress={withdraw} disabled={submitting} style={s.button}><Text style={s.buttonText}>{submitting?'Submitting…':'Withdraw'}</Text></Pressable></View><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>Back</Text></Pressable></ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f5f7f5'},page:{padding:22,paddingBottom:40},brand:{fontSize:29,fontWeight:'900',color:'#0f5b32'},eyebrow:{marginTop:30,fontSize:10,fontWeight:'900',letterSpacing:2,color:'#0f7a3f'},title:{fontSize:29,fontWeight:'900',color:'#142019',marginTop:7},copy:{fontSize:13,lineHeight:20,color:'#718078',marginTop:6,marginBottom:16},card:{backgroundColor:'#fff',borderRadius:22,borderWidth:1,borderColor:'#e5ebe7',padding:18},label:{fontSize:12,fontWeight:'800',color:'#294235',marginTop:14},input:{height:50,borderWidth:1,borderColor:'#dce5df',borderRadius:14,paddingHorizontal:14,marginTop:7,color:'#142019',backgroundColor:'#fbfcfb'},hint:{fontSize:10,color:'#89958e',marginTop:5},secondary:{marginTop:12,borderRadius:14,borderWidth:1,borderColor:'#b8d4c1',padding:14,alignItems:'center'},secondaryText:{fontWeight:'900',color:'#0f5b32'},verified:{marginTop:12,borderRadius:14,backgroundColor:'#edf8f0',padding:13},verifiedTitle:{fontSize:11,fontWeight:'900',color:'#0f7a3f'},verifiedName:{fontSize:14,fontWeight:'800',color:'#173b26',marginTop:3},button:{marginTop:20,borderRadius:15,backgroundColor:'#0f5b32',padding:16,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'900'},error:{color:'#b42318',fontSize:12,marginTop:12},success:{color:'#0f7a3f',fontSize:12,marginTop:12},back:{alignItems:'center',padding:18},backText:{color:'#718078',fontWeight:'800'}})
