import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

const cards = [
  ['Users','users','/admin/users','Users'],['KYC pending','kyc_pending','/admin/kyc','Review'],['Active groups','groups_active','/admin/groups','Groups'],['Contributions due','contributions_due','/admin/contributions','Review'],['Contributions paid','contributions_paid','/admin/contributions','Review'],['Upcoming payouts','payouts_upcoming','/admin/payouts','Payouts'],['Payouts paid','payouts_paid','/admin/payouts','Payouts'],['Failed payments','failed_payments','/admin/transactions','Transactions']
] as const

export default async function AdminDashboardPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect('/admin/login'); const {data:role}=await supabase.rpc('get_my_admin_role'); if(!role)redirect('/admin/login'); const {data,error}=await supabase.rpc('admin_dashboard_summary'); const summary=data||{}
 return <div className="p-4 sm:p-6 max-w-[1400px] mx-auto">
  <header className="relative overflow-hidden rounded-2xl border border-[#dce8df] dark:border-[#244b32] bg-white/90 dark:bg-[#0b1d12]/90 backdrop-blur-xl p-5 sm:p-7 mb-5 shadow-[0_16px_48px_rgba(12,49,28,.07)]"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-[#22c55e]/10 blur-3xl"/><div className="relative flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#22c55e] shadow-[0_0_12px_rgba(34,197,94,.8)]"/><p className="text-[10px] font-black tracking-[.22em] text-[#168447] uppercase">Alajo Operations Network</p></div><h1 className="text-3xl sm:text-4xl font-black mt-2 text-[#101712] dark:text-white">Command dashboard</h1><p className="text-sm text-gray-600 dark:text-gray-200 mt-2 max-w-xl">Live operational intelligence for members, verification, contribution cycles and payouts.</p></div><div className="flex gap-2"><Link href="/admin/groups/create" className="inline-flex items-center justify-center rounded-xl bg-[#0f7a3f] px-4 py-2.5 text-xs font-black text-white shadow-[0_10px_28px_rgba(15,122,63,.22)]">Create group <span className="ml-2">→</span></Link><Link href="/admin/settings" className="inline-flex items-center justify-center rounded-xl border border-[#dce5df] dark:border-[#31513d] bg-white/80 dark:bg-[#102419] px-4 py-2.5 text-xs font-bold text-[#168447] dark:text-[#86efac]">Control</Link></div></div></header>
  {error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 text-red-700 dark:border-red-400/30 dark:bg-red-500/10 dark:text-red-100 px-4 py-3 text-xs font-semibold">Unable to load live summary.</div>}
  <section className="grid grid-cols-2 md:grid-cols-4 gap-3">{cards.map(([label,key,href,action],i)=><Link key={key} href={href} className={`admin-dashboard-card group relative overflow-hidden rounded-2xl border border-[#138044] bg-gradient-to-br ${i===0?'from-[#117f42] via-[#0d6838] to-[#083d25]':'from-[#102b1b] via-[#0c2416] to-[#07170e]'} p-4 sm:p-5 text-white shadow-[0_14px_36px_rgba(0,0,0,.20)] transition-all duration-200 hover:-translate-y-1 hover:border-[#4ade80]`}><div className="absolute -right-8 -top-8 h-24 w-24 rounded-full bg-[#22c55e]/15 blur-2xl"/><div className="relative flex justify-between items-center"><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#d8f8e2]">{label}</p><span className="h-8 w-8 rounded-xl flex items-center justify-center text-sm font-black bg-white/10 text-white">{i===0?'◉':i===1?'✓':i===2?'▦':i>=5?'↗':'↘'}</span></div><p className="relative text-3xl font-black mt-5 text-white">{Number(summary[key]||0).toLocaleString()}</p><div className="relative mt-3 flex items-center justify-between text-[10px] text-[#c4dfce]"><span>{action}</span><span className="opacity-0 group-hover:opacity-100 transition-opacity text-[#86efac]">→</span></div></Link>)}</section>
  <section className="mt-5 grid lg:grid-cols-3 gap-3">{[['/admin/contributions','Contributions','Contribution operations','Monitor pending, paid, missed and failed member contributions.','◌'],['/admin/payouts','Payouts','Payout operations','Track upcoming, processing, completed and failed payouts.','↗'],['/admin/kyc','Compliance','KYC review','Monitor pending and under-review identity verification.','✓']].map(([href,kicker,title,body,icon])=><Link key={href} href={href} className="group relative overflow-hidden rounded-2xl border border-[#e1e9e4] dark:border-[#213f2b] bg-white/90 dark:bg-[#0b1d12]/90 p-5 hover:-translate-y-1 hover:border-[#9ad7ad] dark:hover:border-[#37784e]"><div className="flex items-start justify-between"><div><p className="text-[9px] font-black tracking-[.18em] text-[#168447] uppercase">{kicker}</p><h2 className="text-lg font-black mt-2 text-[#101712] dark:text-white">{title}</h2></div><span className="h-9 w-9 rounded-xl bg-[#edf8f0] dark:bg-[#123421] text-[#168447] dark:text-[#86efac] flex items-center justify-center font-black">{icon}</span></div><p className="text-sm text-gray-600 dark:text-gray-200 mt-3 leading-6">{body}</p><span className="inline-flex items-center mt-5 text-xs font-black text-[#168447] dark:text-[#86efac] group-hover:translate-x-1">Open <span className="ml-2">→</span></span></Link>)}</section>
 </div>
}
