'use client'

import { useEffect, useState } from 'react'
import { AlajoIcon } from '@/components/ui/alajo-icon'
import { UserPageShell } from '@/components/layout/user-page-shell'
import { FundingAccountCard } from '@/components/wallet/funding-account-card'

const money=(value:number)=>`₦${Number(value||0).toLocaleString('en-NG',{minimumFractionDigits:2})}`
type DashboardResponse={wallet?:{balance?:number}}
type Bank={code:string;name:string;slug?:string}

export default function WalletPage(){
 const[balance,setBalance]=useState(0),[loading,setLoading]=useState(true),[amount,setAmount]=useState(''),[bankCode,setBankCode]=useState(''),[accountNumber,setAccountNumber]=useState(''),[accountName,setAccountName]=useState(''),[verified,setVerified]=useState(false),[verifying,setVerifying]=useState(false),[submitting,setSubmitting]=useState(false),[message,setMessage]=useState(''),[banks,setBanks]=useState<Bank[]>([])
 useEffect(()=>{fetch('/api/dashboard',{cache:'no-store'}).then(async r=>{if(r.status===401){window.location.replace('/login');return}const d:DashboardResponse=r.ok?await r.json():{};setBalance(Number(d.wallet?.balance??0))}).catch(()=>setBalance(0)).finally(()=>setLoading(false)); fetch('/api/kyc/banks',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>setBanks(d?.banks??[])).catch(()=>setBanks([]))},[])
 function resetVerification(){setVerified(false);setAccountName('');setMessage('')}
 async function verifyAccount(){setMessage('');setVerified(false);if(!bankCode||!/^\d{10}$/.test(accountNumber)){setMessage('Select your bank and enter a valid 10-digit account number.');return}setVerifying(true);try{const r=await fetch('/api/v1/me/payout-account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bankCode,accountNumber})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.verified)throw new Error(d.error||'Unable to verify this account.');setAccountName(d.accountName);setVerified(true);setMessage('Account verified successfully.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to verify this account.')}finally{setVerifying(false)}}
 async function withdraw(){setMessage('');const value=Number(amount);if(!Number.isFinite(value)||value<=0){setMessage('Enter a valid amount.');return}if(value>balance){setMessage('Amount is greater than your available wallet balance.');return}if(!verified||!accountName){setMessage('Verify your bank account before withdrawing.');return}setSubmitting(true);try{const r=await fetch('/api/v1/me/payout-request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount:value,bankCode,accountNumber,accountName})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.error||'Withdrawal failed.');setMessage('Withdrawal request submitted and reserved for processing.');setAmount('')}catch(e){setMessage(e instanceof Error?e.message:'Withdrawal failed.')}finally{setSubmitting(false)}}
 return <UserPageShell eyebrow="Wallet" title="Wallet" description="Your wallet balance, virtual account and withdrawals." actions={<div className="h-9 w-9 rounded-full bg-[#e8f6ed] text-[#15803d] flex items-center justify-center"><AlajoIcon name="wallet" size={17}/></div>}>
  <div className="max-w-2xl space-y-5">
   <section className="bg-white rounded-2xl border border-[#e3e9e5] p-5 sm:p-7 shadow-[0_8px_30px_rgba(16,37,26,.05)]"><p className="text-[10px] uppercase tracking-[.16em] font-bold text-[#15803d]">Wallet balance</p><p className="text-[32px] font-extrabold text-[#10251a] mt-2">{loading?'—':money(balance)}</p></section>
   <section className="bg-white rounded-2xl border border-[#e3e9e5] p-5 sm:p-7 shadow-[0_8px_30px_rgba(16,37,26,.05)]"><h2 className="font-bold text-[#10251a] text-[19px]">Your ZeePay virtual account</h2><p className="text-[#68766e] text-[12px] mt-1">Transfer any amount from your bank app directly to this account. Your wallet is credited automatically after Paystack confirms the transfer.</p><FundingAccountCard /></section>
   <section className="bg-white rounded-2xl border border-[#e3e9e5] p-5 sm:p-7 shadow-[0_8px_30px_rgba(16,37,26,.05)]"><p className="text-[10px] uppercase tracking-[.16em] font-bold text-[#15803d]">Withdraw</p><h2 className="font-bold text-[#10251a] text-[19px] mt-1">Withdraw from wallet</h2><div className="mt-4 space-y-3"><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="Amount (₦)" className="h-11 w-full rounded-xl border border-[#dfe7e2] px-3 text-sm outline-none focus:border-[#15803d]"/><select value={bankCode} onChange={e=>{setBankCode(e.target.value);resetVerification()}} className="h-11 w-full rounded-xl border border-[#dfe7e2] bg-white px-3 text-sm outline-none focus:border-[#15803d]"><option value="">Choose your bank</option>{banks.map(b=><option key={b.code} value={b.code}>{b.name}</option>)}</select><input value={accountNumber} onChange={e=>{setAccountNumber(e.target.value.replace(/\D/g,'').slice(0,10));setVerified(false);setAccountName('')}} inputMode="numeric" placeholder="10-digit account number" className="h-11 w-full rounded-xl border border-[#dfe7e2] px-3 text-sm outline-none focus:border-[#15803d]"/><button type="button" onClick={verifyAccount} disabled={verifying||!bankCode||accountNumber.length!==10} className="h-11 w-full rounded-xl border border-[#15803d] text-[#0f5b32] text-sm font-semibold disabled:opacity-50">{verifying?'Verifying with Paystack…':'Verify account'}</button>{verified&&<div className="rounded-xl border border-[#cde8d5] bg-[#f2fbf5] p-3"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#15803d]">✓ Account verified</p><p className="mt-1 text-sm font-semibold text-[#10251a]">{accountName}</p><p className="text-xs text-[#68766e]">{banks.find(b=>b.code===bankCode)?.name} · {accountNumber}</p></div>}</div><button onClick={withdraw} disabled={submitting||loading||!verified} className="mt-4 w-full h-11 rounded-xl bg-[#0f5b32] text-white text-sm font-semibold disabled:opacity-50">{submitting?'Processing…':`Withdraw ${amount?money(Number(amount)):''}`}</button>{message&&<p className="mt-3 text-xs text-[#68766e]">{message}</p>}<p className="mt-3 text-[10px] text-[#9aa59f]">Your bank account is verified by Paystack before a withdrawal can be submitted.</p></section>
  </div>
 </UserPageShell>
}
