'use client'

import { useEffect, useState } from 'react'
import { AlajoIcon } from '@/components/ui/alajo-icon'
import { UserPageShell } from '@/components/layout/user-page-shell'
import { FundingAccountCard } from '@/components/wallet/funding-account-card'

const money=(value:number)=>`₦${Number(value||0).toLocaleString('en-NG',{minimumFractionDigits:2})}`
type DashboardResponse={wallet?:{balance?:number}}

export default function WalletPage(){
 const[balance,setBalance]=useState(0),[loading,setLoading]=useState(true),[amount,setAmount]=useState(''),[bankCode,setBankCode]=useState(''),[accountNumber,setAccountNumber]=useState(''),[accountName,setAccountName]=useState(''),[submitting,setSubmitting]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{fetch('/api/dashboard',{cache:'no-store'}).then(async r=>{if(r.status===401){window.location.replace('/login');return}const d:DashboardResponse=r.ok?await r.json():{};setBalance(Number(d.wallet?.balance??0))}).catch(()=>setBalance(0)).finally(()=>setLoading(false))},[])
 async function withdraw(){setMessage(''); const value=Number(amount); if(!Number.isFinite(value)||value<=0){setMessage('Enter a valid amount.');return} if(value>balance){setMessage('Amount is greater than your available wallet balance.');return} if(!/^\d{10}$/.test(accountNumber)||!bankCode||!accountName){setMessage('Enter your bank code, 10-digit account number and verified account name.');return} setSubmitting(true); try { const r=await fetch('/api/v1/me/payout-request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount:value,bankCode,accountNumber,accountName})}); const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(d.detail||d.error||'Withdrawal failed.'); setMessage(d.status==='PROCESSING'?'Withdrawal submitted and is being processed.':'Withdrawal request submitted.'); setAmount('') } catch(e){setMessage(e instanceof Error?e.message:'Withdrawal failed.')} finally{setSubmitting(false)} }
 return <UserPageShell eyebrow="Wallet" title="Wallet" description="Your wallet balance, virtual account and withdrawals." actions={<div className="h-9 w-9 rounded-full bg-[#e8f6ed] text-[#15803d] flex items-center justify-center"><AlajoIcon name="wallet" size={17}/></div>}>
  <div className="max-w-2xl space-y-5">
   <section className="bg-white rounded-2xl border border-[#e3e9e5] p-5 sm:p-7 shadow-[0_8px_30px_rgba(16,37,26,.05)]"><p className="text-[10px] uppercase tracking-[.16em] font-bold text-[#15803d]">Wallet balance</p><p className="text-[32px] font-extrabold text-[#10251a] mt-2">{loading?'—':money(balance)}</p></section>
   <section className="bg-white rounded-2xl border border-[#e3e9e5] p-5 sm:p-7 shadow-[0_8px_30px_rgba(16,37,26,.05)]"><h2 className="font-bold text-[#10251a] text-[19px]">Your ZeePay virtual account</h2><p className="text-[#68766e] text-[12px] mt-1">Transfer any amount from your bank app directly to this account. Your wallet is credited automatically after Paystack confirms the transfer.</p><FundingAccountCard /></section>
   <section className="bg-white rounded-2xl border border-[#e3e9e5] p-5 sm:p-7 shadow-[0_8px_30px_rgba(16,37,26,.05)]"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.16em] font-bold text-[#15803d]">Withdraw</p><h2 className="font-bold text-[#10251a] text-[19px] mt-1">Withdraw from wallet</h2></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="Amount (₦)" className="h-11 rounded-xl border border-[#dfe7e2] px-3 text-sm outline-none focus:border-[#15803d]"/><input value={bankCode} onChange={e=>setBankCode(e.target.value)} placeholder="Bank code" className="h-11 rounded-xl border border-[#dfe7e2] px-3 text-sm outline-none focus:border-[#15803d]"/><input value={accountNumber} onChange={e=>setAccountNumber(e.target.value.replace(/\D/g,'').slice(0,10))} inputMode="numeric" placeholder="10-digit account number" className="h-11 rounded-xl border border-[#dfe7e2] px-3 text-sm outline-none focus:border-[#15803d]"/><input value={accountName} onChange={e=>setAccountName(e.target.value)} placeholder="Account name" className="h-11 rounded-xl border border-[#dfe7e2] px-3 text-sm outline-none focus:border-[#15803d]"/></div><button onClick={withdraw} disabled={submitting||loading} className="mt-4 w-full h-11 rounded-xl bg-[#0f5b32] text-white text-sm font-semibold disabled:opacity-50">{submitting?'Processing…':'Withdraw'}</button>{message&&<p className="mt-3 text-xs text-[#68766e]">{message}</p>}<p className="mt-3 text-[10px] text-[#9aa59f]">Only withdraw funds that are available in your ZeePay wallet. Bank details are processed server-side.</p></section>
  </div>
 </UserPageShell>
}
