'use client'

import { useEffect, useMemo, useState } from 'react'
import { UserPageShell } from '@/components/layout/user-page-shell'
import { AlajoIcon } from '@/components/ui/alajo-icon'

type Transaction = { id:string; type:string; amount:number; currency:string; status:string; provider:string|null; reference:string|null; date:string; groupId:string|null; contributionId:string|null; description?:string; source?:string }
const naira=(amount:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:2}).format(amount)
const label=(type:string)=>type==='wallet_funding'?'Wallet funding':type.replaceAll('_',' ')
const isSuccessful=(status:string)=>['posted','paid','successful','succeeded','completed'].includes(status)
export default function TransactionsPage(){
 const[rows,setRows]=useState<Transaction[]>([]),[filter,setFilter]=useState<'all'|'contribution'|'payout'|'wallet_funding'>('all'),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{fetch('/api/transactions',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load transactions');setRows(d.transactions??[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 const filtered=useMemo(()=>filter==='all'?rows:rows.filter(r=>r.type===filter),[rows,filter])
 const total=rows.filter(r=>isSuccessful(r.status)).reduce((sum,r)=>sum+r.amount,0)
 return <UserPageShell eyebrow="Activity" title="My Transactions" description="Your wallet, contribution and payout activity." actions={<a href="/wallet" className="rounded-xl bg-[#0f5b32] px-4 py-2.5 text-[12px] font-bold text-white transition hover:-translate-y-0.5 active:scale-[.98]">Fund Wallet</a>}><div className="mx-auto w-full max-w-[1180px]"><section className="grid gap-3 md:grid-cols-3"><div className="rounded-2xl border border-[#e3e9e5] bg-white p-5"><p className="text-[10px] uppercase tracking-wide font-bold text-[#8a958f]">Transactions</p><p className="mt-2 text-2xl font-bold text-[#10251a]">{rows.length}</p></div><div className="rounded-2xl border border-[#e3e9e5] bg-white p-5"><p className="text-[10px] uppercase tracking-wide font-bold text-[#8a958f]">Successful value</p><p className="mt-2 text-xl sm:text-2xl font-bold text-[#10251a]">{naira(total)}</p></div><div className="rounded-2xl border border-[#e3e9e5] bg-white p-5"><p className="text-[10px] uppercase tracking-wide font-bold text-[#8a958f]">Contributions</p><p className="mt-2 text-2xl font-bold text-[#10251a]">{rows.filter(r=>r.type==='contribution').length}</p></div></section><section className="mt-5 overflow-hidden rounded-2xl border border-[#e3e9e5] bg-white"><div className="flex flex-wrap gap-2 border-b border-[#edf0ee] p-4">{(['all','contribution','payout','wallet_funding'] as const).map(item=><button key={item} onClick={()=>setFilter(item)} className={`rounded-xl px-4 py-2 text-[11px] font-bold capitalize transition active:scale-[.97] ${filter===item?'bg-[#0f5b32] text-white':'bg-[#f2f5f3] text-[#637168] hover:bg-[#eaf7ef] hover:text-[#126b39]'}`}>{label(item)}</button>)}</div>{loading?<div className="p-8 text-[12px] text-[#68766e]">Loading transactions…</div>:error?<div className="p-8 text-[12px] text-red-600">{error}</div>:filtered.length===0?<div className="p-10 text-center text-[12px] text-[#68766e]">No transactions recorded yet.</div>:<div className="divide-y divide-[#edf0ee]">{filtered.map(tx=><div key={`${tx.source}-${tx.id}`} className="flex flex-col gap-3 p-4 sm:p-5 md:flex-row md:items-center md:justify-between transition hover:bg-[#fafcfb]"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#eaf7ef] text-[#16a34a]"><AlajoIcon name={tx.type==='payout'?'payouts':tx.type==='contribution'?'contributions':'wallet'} size={17}/></div><div><p className="font-bold text-[#183526] text-[13px] capitalize">{label(tx.type)}</p><p className="text-[10px] text-[#8a958f] mt-0.5">{tx.description||tx.reference||new Date(tx.date).toLocaleString('en-NG')}</p></div></div><div className="text-left md:text-right"><p className="font-bold text-[#10251a] text-[13px]">{naira(tx.amount)}</p><p className="text-[10px] capitalize text-[#68766e]">{tx.status.replaceAll('_',' ')}</p></div></div>)}</div>}</section></div></UserPageShell>
}
