'use client'

import { useEffect, useState } from 'react'

const money=(n:number)=>`₦${Number(n||0).toLocaleString('en-NG',{minimumFractionDigits:2})}`
export default function AdminWalletsPage(){
 const[data,setData]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{fetch('/api/admin/finance',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load wallets');setData(d.wallets??[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 return <section className="p-5 sm:p-8 max-w-6xl mx-auto"><p className="text-xs font-bold tracking-[.2em] text-[#16a34a]">FINANCE</p><h1 className="text-3xl font-bold mt-2">Wallets</h1><p className="text-gray-500 dark:text-gray-400 mt-2">Authoritative wallet balances and funding state.</p><div className="mt-8 rounded-2xl border border-gray-200 bg-white overflow-hidden"><div className="p-5 border-b border-gray-100"><p className="font-semibold">Wallet balances</p></div>{loading?<p className="p-8 text-sm text-gray-500">Loading wallets…</p>:error?<p className="p-8 text-sm text-red-600">{error}</p>:data.length===0?<p className="p-8 text-sm text-gray-500">No wallets found.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-gray-50 text-gray-500 uppercase tracking-wide"><tr><th className="px-5 py-3">User</th><th className="px-5 py-3">Currency</th><th className="px-5 py-3">Balance</th><th className="px-5 py-3">Updated</th></tr></thead><tbody className="divide-y divide-gray-100">{data.map(w=><tr key={w.id}><td className="px-5 py-4"><p className="font-semibold text-gray-900">{w.user?.full_name||'User'}</p><p className="text-gray-400">{w.user?.email||w.user_id}</p></td><td className="px-5 py-4">{w.currency}</td><td className="px-5 py-4 font-bold">{money(w.balance)}</td><td className="px-5 py-4 text-gray-500">{new Date(w.updated_at).toLocaleString('en-NG')}</td></tr>)}</tbody></table></div>}</div></section>
}
