import Link from 'next/link'

const Section=({id,title,children}:{id?:string;title:string;children:React.ReactNode})=><section id={id} className="mt-10"><h2 className="text-xl font-extrabold text-[#132018]">{title}</h2><div className="mt-3 space-y-3 text-sm leading-7 text-[#5f6d64]">{children}</div></section>

export default function PrivacyPage(){return <main className="min-h-screen bg-[#f6f8f6] text-[#132018]"><div className="mx-auto max-w-4xl px-5 py-10 sm:px-8 sm:py-14"><Link href="/legal" className="text-sm font-semibold text-[#15803d]">← Legal Centre</Link><header className="mt-8"><div className="flex items-center gap-3"><img src="/icons/zeepay.svg" alt="ZeePay" className="h-12 w-12 rounded-xl"/><div><p className="text-xs font-bold tracking-[.16em] text-[#e85d04]">ZEEPAY</p><h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl">Privacy Policy</h1></div></div><p className="mt-4 text-sm text-[#77837c]">Effective date: 16 August 2026</p></header>
<Section title="1. Scope"><p>This Privacy Policy explains how ZeePay collects, uses, stores, protects and shares information when you use the website, application, savings groups, wallet functionality and related services.</p></Section>
<Section title="2. Information we collect"><p>We may collect account information such as your name, email address, phone number, password-related authentication data and profile information.</p><p>For KYC and financial functionality, we may process identity and verification information such as date of birth, BVN, identity-document information, verification responses, bank or account details and information needed to satisfy fraud, compliance or onboarding requirements.</p><p>We also collect transaction and platform information such as payment references, contribution records, wallet ledger entries, group memberships, payout positions, default/recovery records, temporary payout-cover records, device/browser information, IP address and security events.</p></Section>
<Section id="kyc" title="3. KYC and BVN processing"><p>Identity information is processed only for defined purposes such as identity verification, account security, fraud prevention, regulatory compliance, account opening and access to financial features.</p><p>Where a bank, KYC provider or regulated financial partner performs verification, we may send the minimum information necessary to obtain the required verification response. The provider's own privacy notice may also apply.</p><p>We do not treat KYC information as ordinary marketing data. Access is restricted according to role, operational need and security controls.</p></Section>
<Section title="4. How we use information"><p>We use information to create and secure accounts, operate savings groups, process and reconcile payments, maintain the wallet ledger, verify identity, detect fraud, manage contribution defaults and recovery, provide customer support, send transactional notifications, improve reliability and meet legal or regulatory obligations.</p><p>Where permitted by applicable law and necessary for a qualifying obligation, we may use relevant identity and payment information to support credit-information reporting to licensed credit bureaux or authorised credit-information systems. Any such reporting will follow applicable notice, consent, accuracy, correction and retention requirements.</p></Section>
<Section title="5. Sharing"><p>We may share relevant information with service providers and regulated partners where necessary to provide the service. Depending on the feature, these may include KYC/identity providers, banks, payment processors, licensed credit bureaux or authorised credit-information providers, email/SMS providers, hosting infrastructure and security services.</p><p>We do not sell personal information as a business model. We will not disclose recovery information to unrelated third parties merely to pressure a user to pay.</p></Section>
<Section title="6. Security"><p>We use access controls, server-side validation, authenticated database policies, transaction verification, audit records and other technical and organisational safeguards. No internet service can guarantee absolute security, so users must also protect their credentials and devices.</p></Section>
<Section title="7. Retention"><p>We retain information for as long as reasonably necessary for the purposes described in this policy, including legal, accounting, fraud-prevention, dispute-resolution, recovery and regulatory requirements. Retention periods may differ for identity, transaction, default/recovery and account records.</p></Section>
<Section title="8. Your choices and rights"><p>Subject to applicable law and legitimate retention requirements, you may request access to, correction of or clarification about personal information we hold about you. You may also ask questions about how your information is processed or shared and exercise other data-subject rights available under applicable Nigerian data-protection law.</p></Section>
<Section title="9. Cookies and device data"><p>The application may use essential cookies or local storage for authentication, preferences, security and service functionality. We may also process technical device information for reliability and abuse prevention.</p></Section>
<Section title="10. Children"><p>ZeePay is intended for users who are legally eligible to use the relevant financial and savings services. We do not knowingly create financial accounts for children where doing so would be unlawful or contrary to provider requirements.</p></Section>
<Section title="11. Changes to this policy"><p>We may update this policy when our services, banking partners, KYC arrangements, recovery processes or legal obligations change. The effective date at the top will be updated when a new version is published.</p></Section>
<footer className="mt-14 border-t border-[#dfe7e1] pt-6 text-xs text-[#7a857e]">This Privacy Policy is a product privacy draft for ZeePay and should be reviewed against the final Nigerian operating structure, banking partner, KYC provider, credit-information arrangements and applicable privacy requirements before commercial launch.</footer></div></main>}
