import Link from 'next/link'

const documents = [
  ['Terms & Conditions','The rules governing your Deotech Finance account, savings groups, contributions, payouts and use of the platform.','/terms'],
  ['Privacy Policy','How Deotech Finance collects, uses, stores and shares personal, identity, KYC and transaction information.','/privacy'],
  ['KYC & Identity Notice','How identity information such as BVN, NIN and verification results may be processed through approved providers.','/privacy#kyc'],
  ['Savings Group Rules','The operational rules for group size, closure, slot selection, remapping, contributions and payouts.','/terms#groups'],
  ['Payment & Wallet Notice','How wallet credits, payment verification, reversals, ledger entries and future banking partners are handled.','/terms#wallet'],
]

export default function LegalPage(){return <main className="min-h-screen bg-[#f6f8f6] text-[#132018]"><div className="mx-auto max-w-5xl px-5 py-10 sm:px-8 sm:py-14"><header className="flex items-center justify-between gap-4"><Link href="/" className="flex items-center gap-3"><img src="/icons/deotech-finance.svg" alt="Deotech Finance" className="h-11 w-11 rounded-xl"/><span className="font-extrabold tracking-tight">DEOTECH <span className="text-[#e85d04]">FINANCE</span></span></Link><Link href="/signup" className="rounded-xl bg-[#123524] px-4 py-2.5 text-sm font-semibold text-white">Create account</Link></header><section className="mt-14 max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#e85d04]">Legal & compliance</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight sm:text-5xl">Deotech Finance Legal Centre</h1><p className="mt-5 text-base leading-7 text-[#617066]">These documents explain how Deotech Finance operates and how we handle accounts, savings groups, payments, wallets and identity verification. They are written for the current product model and should be reviewed by qualified Nigerian legal and compliance advisers before commercial launch.</p></section><div className="mt-10 grid gap-4 md:grid-cols-2">{documents.map(([title,text,href])=><Link key={title} href={href} className="rounded-2xl border border-[#dfe7e1] bg-white p-6 shadow-sm hover:border-[#b9d8c4]"><h2 className="text-lg font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-[#68756d]">{text}</p><span className="mt-4 inline-block text-sm font-bold text-[#15803d]">Read document →</span></Link>)}</div><p className="mt-10 text-xs leading-5 text-[#7a857e]">Last updated: 13 August 2026. Deotech Finance may update these documents as its banking, KYC, payment and regulatory arrangements evolve. Where a regulated financial institution or licensed service provider performs a regulated function, its applicable terms and disclosures may also apply.</p></div></main>}
