import Link from 'next/link'

const Section=({id,title,children}:{id?:string;title:string;children:React.ReactNode})=><section id={id} className="mt-10"><h2 className="text-xl font-extrabold text-[#132018]">{title}</h2><div className="mt-3 space-y-3 text-sm leading-7 text-[#5f6d64]">{children}</div></section>

export default function TermsPage(){return <main className="min-h-screen bg-[#f6f8f6] text-[#132018]"><div className="mx-auto max-w-4xl px-5 py-10 sm:px-8 sm:py-14"><Link href="/legal" className="text-sm font-semibold text-[#15803d]">← Legal Centre</Link><header className="mt-8"><div className="flex items-center gap-3"><img src="/icons/deotech-finance.svg" alt="Deotech Finance" className="h-12 w-12 rounded-xl"/><div><p className="text-xs font-bold tracking-[.16em] text-[#e85d04]">DEOTECH FINANCE</p><h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl">Terms & Conditions</h1></div></div><p className="mt-4 text-sm text-[#77837c]">Effective date: 13 August 2026</p></header>
<Section title="1. About these terms"><p>These Terms & Conditions govern access to and use of Deotech Finance, a digital platform for organised rotational savings groups and related financial services. By creating an account or using the platform, you agree to these terms.</p><p>Deotech Finance is not a bank merely because the platform displays wallet or account information. Any regulated banking, payment, account-opening or custody service may be provided by a regulated partner under the partner's applicable terms.</p></Section>
<Section title="2. Eligibility and account security"><p>You must provide accurate information, maintain control of your account credentials and promptly tell us if you suspect unauthorised access. You must not create an account using another person's identity or provide false KYC information.</p></Section>
<Section title="3. Identity and KYC"><p>Access to some or all financial functionality may require identity verification. We may request information including name, date of birth, phone number, BVN, NIN, identification documents and verification results where required by law, our risk controls or a regulated provider.</p><p>Verification may be performed by Deotech Finance or by an approved third-party KYC, banking or payment provider. We may restrict account functionality until required checks are completed.</p></Section>
<Section id="groups" title="4. Savings groups"><p>Groups are created with a maximum capacity of 10 members and a minimum final membership of 5 members. A group may close with any final membership from 5 through 10.</p><p>A user may leave an eligible group before the group closes. Once a group is closed and its cycle is finalised, membership is locked and users cannot leave through the normal self-service flow. An administrator may delete a group only while it remains eligible for deletion and before closure.</p><p>A group that was created with a 10-month maximum does not automatically become a 10-month cycle. At closure, the system uses the actual number of participating members: 5 members creates a 5-month cycle, 6 creates 6 months, and so on up to 10.</p><p>Original slot selection is retained for auditability. If sparse slots are selected, final payout positions are remapped contiguously in the order of the participating members' selected slots. For example, original slots 2, 4, 5, 7, 8, 9 and 10 become final payout positions 1 through 7.</p></Section>
<Section title="5. Contributions and payouts"><p>Users are responsible for making required contributions by the stated due dates. A contribution obligation may be recorded only against the user's actual group membership and the finalised schedule.</p><p>Payout timing and amount depend on the applicable group schedule, successful contributions, payment settlement and any permitted risk or compliance controls. Deotech Finance does not promise a return beyond the rules displayed for the applicable savings group.</p></Section>
<Section id="wallet" title="6. Payments and wallet"><p>Payment providers and banking partners may be used to collect, verify, settle or return funds. A future dedicated virtual account may serve as a user's funding rail, but the Deotech Finance ledger remains the application record of wallet credits and debits.</p><p>We may delay, reject, reverse or investigate a transaction where payment evidence is incomplete, a transaction is duplicated, reversed, disputed, suspected to be fraudulent, or fails required verification.</p><p>Wallet balances must not be manipulated through client-side requests. Financial credits and debits are recorded through authorised server-side operations and auditable ledger entries.</p></Section>
<Section title="7. Prohibited activity"><p>Fraud, identity impersonation, account enumeration, unauthorised access, manipulation of balances or group positions, payment replay, exploitation of race conditions, and attempts to bypass KYC or security controls are prohibited.</p></Section>
<Section title="8. Suspension and termination"><p>We may restrict or suspend functionality where required for security, fraud prevention, KYC, regulatory compliance, payment investigation or violation of these terms. Where practical, we will provide an explanation and a route for resolution.</p></Section>
<Section title="9. Third-party services"><p>Payment, banking, KYC, communications and infrastructure providers may have separate terms and privacy notices. Deotech Finance will only rely on providers appropriate to the service being offered and applicable legal requirements.</p></Section>
<Section title="10. Disputes and support"><p>Users should first contact Deotech Finance through the support channel provided in the application so that the matter can be investigated. Nothing in these terms removes rights that cannot lawfully be excluded under applicable Nigerian law.</p></Section>
<Section title="11. Changes"><p>We may update these terms as the platform, regulatory environment, banking arrangements or product features change. Material changes will be communicated through the application or another appropriate channel.</p></Section>
<footer className="mt-14 border-t border-[#dfe7e1] pt-6 text-xs text-[#7a857e]">This document is a product terms draft for Deotech Finance and is not a substitute for review by qualified Nigerian counsel and compliance advisers.</footer></div></main>}
