import Link from 'next/link'

const Section=({id,title,children}:{id?:string;title:string;children:React.ReactNode})=><section id={id} className="mt-10"><h2 className="text-xl font-extrabold text-[#132018]">{title}</h2><div className="mt-3 space-y-3 text-sm leading-7 text-[#5f6d64]">{children}</div></section>

export default function TermsPage(){return <main className="min-h-screen bg-[#f6f8f6] text-[#132018]"><div className="mx-auto max-w-4xl px-5 py-10 sm:px-8 sm:py-14"><Link href="/legal" className="text-sm font-semibold text-[#15803d]">← Legal Centre</Link><header className="mt-8"><div className="flex items-center gap-3"><img src="/icons/zeepay.svg" alt="ZeePay" className="h-12 w-12 rounded-xl"/><div><p className="text-xs font-bold tracking-[.16em] text-[#e85d04]">ZEEPAY</p><h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl">Terms & Conditions</h1></div></div><p className="mt-4 text-sm text-[#77837c]">Effective date: 16 August 2026</p></header>
<Section title="1. About these terms"><p>These Terms & Conditions govern access to and use of ZeePay, a digital platform for organised rotational savings groups and related financial services. By creating an account or using the platform, you agree to these terms.</p><p>ZeePay is not a bank merely because the platform displays wallet or account information. Any regulated banking, payment, account-opening or custody service may be provided by a regulated partner under the partner's applicable terms.</p></Section>
<Section title="2. Eligibility and account security"><p>You must provide accurate information, maintain control of your account credentials and promptly tell us if you suspect unauthorised access. You must not create an account using another person's identity or provide false KYC information.</p></Section>
<Section title="3. Identity and KYC"><p>Access to some or all financial functionality may require identity verification. We may request information including name, date of birth, phone number, BVN, identification documents and verification results where required by law, our risk controls or a regulated provider.</p><p>Verification may be performed by ZeePay or by an approved third-party KYC, banking or payment provider. We may restrict account functionality until required checks are completed.</p></Section>
<Section id="groups" title="4. Savings groups"><p>Groups are created with a maximum capacity of 10 members and a minimum final membership of 5 members. A group may close with any final membership from 5 through 10.</p><p>A user may leave an eligible group before the group closes. Once a group is closed and its cycle is finalised, membership is locked and users cannot leave through the normal self-service flow. An administrator may delete a group only while it remains eligible for deletion and before closure.</p><p>A group that was created with a 10-month maximum does not automatically become a 10-month cycle. At closure, the system uses the actual number of participating members: 5 members creates a 5-month cycle, 6 creates 6 months, and so on up to 10.</p><p>Original slot selection is retained for auditability. If sparse slots are selected, final payout positions are remapped contiguously in the order of the participating members' selected slots.</p></Section>
<Section title="5. Contributions and payouts"><p>Users are responsible for making required contributions by the stated due dates. A contribution obligation may be recorded only against the user's actual group membership and the finalised schedule.</p><p>Payout timing and amount depend on the applicable group schedule, successful contributions, payment settlement and any permitted risk or compliance controls. ZeePay does not promise a return beyond the rules displayed for the applicable savings group.</p></Section>
<Section id="defaults" title="6. Missed contributions, default and recovery"><p>A contribution that is not paid by its due date may become overdue. ZeePay provides a standard <strong>30-day recovery window</strong> from the missed due date before a contribution is treated as a formal default under the automated default process. Applicable delay fees, if any, continue according to the fee schedule displayed to the user.</p><p><strong>Default before payout:</strong> where a member has not received their scheduled payout and remains unpaid after the recovery window, ZeePay may remove the member from the active cycle. The member's unpaid future schedules are cancelled, the remaining participating members are retained, and the group's future unpaid payout positions and cycle length are recalculated around the surviving members. Paid payout history is not rewritten.</p><p><strong>Default after payout:</strong> where a member has already received their scheduled payout and later fails to make required contributions, the member is not removed in a way that shortens or breaks the group cycle. The cycle continues so that other compliant members can receive their scheduled payouts. Where required to protect a scheduled payout, ZeePay may temporarily fund the contribution shortfall as a separately recorded company cover, while the member's outstanding obligation remains subject to recovery.</p><p>Receiving a payout does not discharge the member's remaining contribution obligations. Outstanding amounts may be pursued through lawful recovery, dispute-resolution and enforcement measures available under the agreement and applicable Nigerian law.</p><p>Where legally permitted and where applicable notice, consent, reporting agreements and other regulatory requirements are satisfied, qualifying default information may be reported to licensed credit bureaux or other authorised credit-information systems. Reporting is not automatic merely because these Terms contain this clause, and users will be given any notice required by applicable law.</p><p>ZeePay will use lawful and non-abusive recovery practices. It will not use public shaming, threats, harassment, unauthorised third-party contact or claims of criminal liability that are not legally established.</p></Section>
<Section id="wallet" title="7. Payments, wallet and company cover"><p>Payment providers and banking partners may be used to collect, verify, settle or return funds. A dedicated virtual account may serve as a user's funding rail, while the ZeePay ledger remains the application record of wallet credits and debits.</p><p>We may delay, reject, reverse or investigate a transaction where payment evidence is incomplete, a transaction is duplicated, reversed, disputed, suspected to be fraudulent, or fails required verification.</p><p>Wallet balances must not be manipulated through client-side requests. Financial credits and debits are recorded through authorised server-side operations and auditable ledger entries.</p><p>Any ZeePay temporary cover used to protect a post-payout member's scheduled group payout is a company-side funding/recovery entry. It does not become a credit to the defaulting member's wallet and does not erase or reduce the member's contractual contribution obligation.</p></Section>
<Section title="8. Prohibited activity"><p>Fraud, identity impersonation, account enumeration, unauthorised access, manipulation of balances or group positions, payment replay, exploitation of race conditions, and attempts to bypass KYC or security controls are prohibited.</p></Section>
<Section title="9. Suspension and termination"><p>We may restrict or suspend functionality where required for security, fraud prevention, KYC, regulatory compliance, payment investigation or violation of these terms. Where practical, we will provide an explanation and a route for resolution.</p></Section>
<Section title="10. Third-party services"><p>Payment, banking, KYC, communications and infrastructure providers may have separate terms and privacy notices. ZeePay will only rely on providers appropriate to the service being offered and applicable legal requirements.</p></Section>
<Section title="11. Disputes and support"><p>Users should first contact ZeePay through the support channel provided in the application so that the matter can be investigated. Nothing in these terms removes rights that cannot lawfully be excluded under applicable Nigerian law.</p></Section>
<Section title="12. Changes"><p>We may update these terms as the platform, regulatory environment, banking arrangements or product features change. Material changes will be communicated through the application or another appropriate channel.</p></Section>
<footer className="mt-14 border-t border-[#dfe7e1] pt-6 text-xs text-[#7a857e]">This document is a product terms draft for ZeePay and is not a substitute for review by qualified Nigerian counsel and compliance advisers. The default and recovery provisions should be reviewed against ZeePay's final regulatory/licensing structure and any credit-bureau reporting arrangements before commercial launch.</footer></div></main>}
