'use client'

import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type User={id:string;full_name:string|null;email:string|null;phone:string|null;status:string|null;onboarding_step:string|null;created_at:string}

export default function UsersTable({users,kycByUser}:{users:User[];kycByUser:Record<string,{status:string}>}){
 const supabase=createClient();const [rows,setRows]=useState(users);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState('')
 async function toggle(user:User){const next=user.status==='suspended'?'active':'suspended';if(!confirm(`${next==='suspended'?'Disable':'Enable'} ${user.email||user.full_name||'this user'}? Financial history, wallet, KYC and group records will be preserved.`))return;setBusy(user.id);setError('');const {error}=await supabase.rpc('admin_set_user_status',{p_user_id:user.id,p_status:next});if(error)setError(error.message);else setRows(prev=>prev.map(r=>r.id===user.id?{...r,status:next}:r));setBusy(null)}
 return <>{error&&<div className="mb-4 rounded-xl border border-red-300/30 bg-red-500/10 p-3 text-sm text-red-200">{error}</div>}<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#102719] text-[#9fb3a8]"><tr><th className="text-left px-5 py-3 font-semibold">User</th><th className="text-left px-5 py-3 font-semibold">Phone</th><th className="text-left px-5 py-3 font-semibold">Account</th><th className="text-left px-5 py-3 font-semibold">KYC</th><th className="text-left px-5 py-3 font-semibold">Joined</th><th className="text-right px-5 py-3 font-semibold">Action</th></tr></thead><tbody className="divide-y divide-[#244332]">{rows.map(user=>{const verified=kycByUser[user.id]?.status==='approved';const disabled=user.status==='suspended';return <tr key={user.id} className="hover:bg-[#102719] transition-colors"><td className="px-5 py-4"><p className="font-semibold text-white">{user.full_name||'Unnamed user'}</p><p className="text-xs text-[#9fb3a8] mt-0.5">{user.email||'—'}</p></td><td className="px-5 py-4 text-[#d6e1da]">{user.phone||'—'}</td><td className="px-5 py-4"><span className={disabled?'text-red-300':'text-[#86efac]'}>{disabled?'Disabled':'Active'}</span><p className="text-xs text-[#879d90] mt-1">{user.onboarding_step||'—'}</p></td><td className="px-5 py-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${verified?'bg-[#123b22] text-[#61e58d]':'bg-[#3a2d10] text-[#f6c85f]'}`}>{verified?'Verified':kycByUser[user.id]?.status?.replaceAll('_',' ')||'Not verified'}</span></td><td className="px-5 py-4 text-[#b7c7be]">{new Intl.DateTimeFormat('en-NG',{dateStyle:'medium'}).format(new Date(user.created_at))}</td><td className="px-5 py-4 text-right"><button disabled={busy===user.id} onClick={()=>toggle(user)} className={`rounded-lg px-3 py-2 text-xs font-bold disabled:opacity-50 ${disabled?'bg-[#123b22] text-[#86efac]':'bg-red-500/10 text-red-300 border border-red-300/20'}`}>{busy===user.id?'Saving…':disabled?'Enable':'Disable'}</button></td></tr>})}</tbody></table></div></>
}
