'use client'

import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type User={id:string;full_name:string|null;email:string|null;phone:string|null;status:string|null;onboarding_step:string|null;created_at:string}

export default function UsersTable({users,kycByUser}:{users:User[];kycByUser:Record<string,{status:string}>}){
 const supabase=createClient();const [rows,setRows]=useState(users);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState('')
 async function toggle(user:User){const next=user.status==='suspended'?'active':'suspended';if(!confirm(`${next==='suspended'?'Disable':'Enable'} ${user.email||user.full_name||'this user'}? Financial history, KYC and group records will be preserved.`))return;setBusy(user.id);setError('');const {error}=await supabase.rpc('admin_set_user_status',{p_user_id:user.id,p_status:next});if(error)setError(error.message);else setRows(prev=>prev.map(r=>r.id===user.id?{...r,status:next}:r));setBusy(null)}
 async function remove(user:User){const label=user.email||user.full_name||'this user';if(!confirm(`Permanently delete ${label}? This removes the user login and account. This cannot be undone.`))return;setBusy(user.id);setError('');const {error}=await supabase.rpc('admin_delete_user',{p_user_id:user.id});if(error)setError(error.message);else setRows(prev=>prev.filter(r=>r.id!==user.id));setBusy(null)}
 return <>{error&&<div className="mb-4 rounded-xl border border-red-300/40 bg-red-500/10 p-3 text-sm text-red-100">{error}</div>}<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#102719] text-[#d2e2d8]"><tr><th className="text-left px-5 py-3 font-semibold">User</th><th className="text-left px-5 py-3 font-semibold">Phone</th><th className="text-left px-5 py-3 font-semibold">Account</th><th className="text-left px-5 py-3 font-semibold">KYC</th><th className="text-left px-5 py-3 font-semibold">Joined</th><th className="text-right px-5 py-3 font-semibold">Actions</th></tr></thead><tbody className="divide-y divide-[#244332]">{rows.map(user=>{const kycStatus=String(kycByUser[user.id]?.status||'NOT_STARTED').toUpperCase();const verified=kycStatus==='VERIFIED';const disabled=user.status==='suspended';return <tr key={user.id} className="hover:bg-[#102719] transition-colors"><td className="px-5 py-4"><p className="font-semibold text-white">{user.full_name||'Unnamed user'}</p><p className="text-xs text-[#c4d3ca] mt-0.5">{user.email||'—'}</p></td><td className="px-5 py-4 text-[#e2ebe5]">{user.phone||'—'}</td><td className="px-5 py-4"><span className={disabled?'text-red-200':'text-[#86efac]'}>{disabled?'Disabled':'Active'}</span><p className="text-xs text-[#aebfb4] mt-1">{user.onboarding_step||'—'}</p></td><td className="px-5 py-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${verified?'bg-[#123b22] text-[#86efac]':'bg-[#3a2d10] text-[#fde68a]'}`}>{verified?'Verified':kycStatus.replaceAll('_',' ').toLowerCase()}</span></td><td className="px-5 py-4 text-[#d4e0d8]">{new Intl.DateTimeFormat('en-NG',{dateStyle:'medium'}).format(new Date(user.created_at))}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button disabled={busy===user.id} onClick={()=>toggle(user)} className={`rounded-lg px-3 py-2 text-xs font-bold disabled:opacity-50 ${disabled?'bg-[#123b22] text-[#86efac]':'bg-red-500/10 text-red-100 border border-red-300/30'}`}>{busy===user.id?'Saving…':disabled?'Enable':'Disable'}</button><button disabled={busy===user.id} onClick={()=>remove(user)} className="rounded-lg px-3 py-2 text-xs font-bold text-red-100 border border-red-400/40 bg-red-950/40 hover:bg-red-900/60 disabled:opacity-50">Delete</button></div></td></tr>})}</tbody></table></div></>
}
