'use client'

import { useEffect, useState } from 'react'
const money=(n:number)=>`₦${Number(n||0).toLocaleString('en-NG',{minimumFractionDigits:2})}`
export default function AdminTransactionsPage(){
 const[data,setData]=useState<any>({payments:[],ledger:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[requerying,setRequerying]=useState(''),[message,setMessage]=useState(''),[reference,setReference]=useState<Record<string,string>>({})
 const load=()=>{setLoading(true);fetch('/api/admin/finance',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load transactions');setData(d)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))}
 useEffect(load,[])
 const requery=async(id:string)=>{setRequerying(id);setMessage('');try{const r=await fetch('/api/admin/payments/requery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({paymentId:id,paystackReference:reference[id]?.trim()||undefined})});const d=await r.json();if(!r.ok){const checks=d.checks?` Amount ${d.checks.amountMatches?'✓':'✗'}, currency ${d.checks.currencyMatches?'✓':'✗'}, environment ${d.checks.domainMatches?'✓':'✗'}, identity ${d.checks.metadataIdentityMatches?'✓':'✗'}. Paystack reference: ${d.paystack?.reference||'not returned'}.`:' ';throw new Error((d.message||d.error||'Unable to requery')+checks)}setMessage(d.status==='settled'?'Payment verified and settled. Wallet credit and ledger settlement completed.':d.status==='still_pending'?'Paystack still reports this payment as pending.':'Payment was not credited.');load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to requery')}finally{setRequerying('')}}
 return <section className="p-5 sm:p-8 max-w-6xl mx-auto"><p className="text-xs font-bold tracking-[.2em] text-[#16a34a]">FINANCE</p><h1 className="text-3xl font-bold mt-2">Transactions</h1><p className="text-gray-500 dark:text-gray-400 mt-2">Payments, wallet credits/debits and reconciliation.</p>{message&&<div className="mt-5 rounded-xl border border-[#d4ecdc] bg-[#eaf7ef] p-4 text-sm font-semibold text-[#14532d] whitespace-pre-wrap">{message}</div>}{loading?<p className="mt-8 text-sm text-gray-500">Loading transactions…</p>:error?<p className="mt-8 text-sm text-red-600">{error}</p>:<div className="mt-8 rounded-2xl border border-gray-200 bg-white overflow-hidden"><div className="p-5 border-b border-gray-100"><p className="font-semibold">Payment activity</p></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-gray-50 text-gray-500 uppercase tracking-wide"><tr><th className="px-5 py-3">User</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Provider / Reference</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Recovery</th></tr></thead><tbody className="divide-y divide-gray-100">{(data.payments??[]).map((p:any)=><tr key={p.id}><td className="px-5 py-4"><p className="font-semibold">{p.user?.full_name||'User'}</p><p className="text-gray-400">{p.user?.email||p.user_id}</p></td><td className="px-5 py-4 font-bold">{money(p.amount)}</td><td className="px-5 py-4"><p>{p.provider}</p><p className="text-gray-400 break-all">{p.provider_reference}</p>{p.provider==='paystack'&&['pending','processing'].includes(p.status)&&<input value={reference[p.id]||''} onChange={e=>setReference(v=>({...v,[p.id]:e.target.value}))} placeholder="Optional Paystack reference" className="mt-2 w-full max-w-xs rounded-lg border border-gray-200 px-3 py-2 text-xs text-gray-900" />}</td><td className="px-5 py-4 capitalize">{String(p.status).replaceAll('_',' ')}</td><td className="px-5 py-4">{['pending','processing'].includes(p.status)&&p.provider==='paystack'?<button onClick={()=>requery(p.id)} disabled={requerying===p.id} className="rounded-lg bg-[#0f5b32] px-3 py-2 font-bold text-white disabled:opacity-50">{requerying===p.id?'Checking…':'Requery'}</button>:<span className="text-gray-400">—</span>}</td></tr>)}</tbody></table></div></div>}</section>
}
