'use client'

import { useEffect, useMemo, useState } from 'react'

const money=(n:number)=>`₦${Number(n||0).toLocaleString('en-NG',{maximumFractionDigits:0})}`
type Case={id:string;status:string;outstanding_amount:number;payout_received:boolean;grace_until:string|null;defaulted_at:string|null;deotech_covered_amount:number;recovered_amount:number;credit_bureau_notice_at:string|null;created_at:string;resolved_at:string|null;user:{name:string;email:string};group:{name:string;cycle:string;finalizedMemberCount:number|null;status:string}|null;payoutPosition:number|null;payoutReceivedAt:string|null;membershipStatus:string|null}

export default function AdminDefaultsPage(){
 const[cases,setCases]=useState<Case[]>([]),[loading,setLoading]=useState(true),[processing,setProcessing]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState<'all'|'pre'|'post'|'resolved'>('all')
 async function load(){setLoading(true);try{const r=await fetch('/api/admin/defaults',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setCases(d.cases||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load recovery cases.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 async function process(){setProcessing(true);setMessage('');setError('');try{const r=await fetch('/api/admin/defaults',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(`Default check completed. ${d.result?.removed_members||0} pre-payout member(s) removed; ${d.result?.recovery_cases||0} post-payout recovery case(s) active; ${d.protection?.protected||0} payout shortfall(s) protected.`);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to process defaults.')}finally{setProcessing(false)}}
 const visible=useMemo(()=>cases.filter(c=>tab==='all'?c.status!=='resolved'&&c.status!=='cancelled':tab==='pre'?!c.payout_received&&c.status!=='resolved'&&c.status!=='cancelled':tab==='post'?c.payout_received&&c.status!=='resolved'&&c.status!=='cancelled':c.status==='resolved'),[cases,tab])
 const active=cases.filter(c=>!['resolved','cancelled'].includes(c.status));const pre=active.filter(c=>!c.payout_received);const post=active.filter(c=>c.payout_received)
 return <main className="min-h-screen bg-[#06130b] text-white p-5 sm:p-8"><div className="max-w-7xl mx-auto"><div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.22em] font-bold text-[#39c66b]">RISK & RECOVERY</p><h1 className="text-3xl sm:text-4xl font-black mt-1">Defaults & Recovery</h1><p className="text-sm text-gray-300 mt-2 max-w-2xl">30-day contribution recovery window. Pre-payout defaults can be removed from the cycle; post-payout defaults never shorten the cycle.</p></div><button onClick={process} disabled={processing} className="rounded-xl bg-[#16a34a] px-5 py-3 text-sm font-bold hover:bg-[#15803d] disabled:opacity-50">{processing?'Processing…':'Run default check'}</button></div>
 <div className="mt-6 grid grid-cols-1 sm:grid-cols-3 gap-3"><Stat label="Active cases" value={active.length}/><Stat label="Pre-payout" value={pre.length}/><Stat label="Post-payout recovery" value={post.length}/></div>
 {message&&<div className="mt-4 rounded-xl border border-[#16a34a]/30 bg-[#16a34a]/10 p-4 text-sm text-[#9af0b4]">{message}</div>}{error&&<div className="mt-4 rounded-xl border border-red-400/30 bg-red-500/10 p-4 text-sm text-red-200">{error}</div>}
 <div className="mt-6 rounded-2xl border border-[#244332] bg-[#0b2113] overflow-hidden"><div className="px-5 pt-4 border-b border-[#244332] flex gap-6 overflow-x-auto">{([['all','Active'],['pre','Pre-payout'],['post','Post-payout recovery'],['resolved','Resolved']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`pb-3 text-xs font-semibold border-b-2 whitespace-nowrap ${tab===k?'text-[#72e89a] border-[#16a34a]':'text-[#8fa79a] border-transparent'}`}>{l}</button>)}</div>
 {loading?<div className="p-10 text-center text-[#9fb3a8]">Loading recovery cases…</div>:visible.length===0?<div className="p-12 text-center"><p className="font-bold">No cases in this view.</p><p className="text-xs text-[#8fa79a] mt-1">Use “Run default check” after a contribution passes its recovery window.</p></div>:<div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-[#102719] text-[#8fa79a]"><tr><th className="text-left px-4 py-3">User</th><th className="text-left px-4 py-3">Group</th><th className="text-left px-4 py-3">Type</th><th className="text-left px-4 py-3">Outstanding</th><th className="text-left px-4 py-3">Deotech cover</th><th className="text-left px-4 py-3">Status</th><th className="text-left px-4 py-3">Grace/default</th></tr></thead><tbody className="divide-y divide-[#244332]">{visible.map(c=><tr key={c.id} className="hover:bg-[#102719]"><td className="px-4 py-4"><p className="font-semibold">{c.user.name}</p><p className="text-[10px] text-[#8fa79a]">{c.user.email||'—'}</p></td><td className="px-4 py-4"><p>{c.group?.name||'Savings group'}</p><p className="text-[10px] text-[#8fa79a] mt-1">{c.group?.finalizedMemberCount||'—'}-member cycle</p></td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 font-semibold ${c.payout_received?'bg-[#143a26] text-[#72e89a]':'bg-[#3a2d10] text-[#f6c85f]'}`}>{c.payout_received?'Post-payout':'Pre-payout'}</span></td><td className="px-4 py-4 font-bold">{money(c.outstanding_amount)}</td><td className="px-4 py-4">{money(c.deotech_covered_amount)}</td><td className="px-4 py-4 capitalize text-[#d5e2da]">{c.status.replaceAll('_',' ')}</td><td className="px-4 py-4 text-[#9fb3a8]">{c.defaulted_at?new Date(c.defaulted_at).toLocaleDateString('en-NG',{day:'2-digit',month:'short',year:'numeric'}):c.grace_until?new Date(c.grace_until).toLocaleDateString('en-NG',{day:'2-digit',month:'short',year:'numeric'}):'—'}</td></tr>)}</tbody></table></div>}
 </div><div className="mt-5 rounded-2xl border border-[#244332] bg-[#0b2113] p-5 text-xs text-[#9fb3a8] leading-6"><p className="font-bold text-white mb-1">Operational rule</p>Pre-payout default: remove the member after the 30-day recovery window and rebuild only the future unpaid schedule/payout positions around the surviving members. Post-payout default: keep the group cycle unchanged, protect due payouts with a separately recorded Deotech cover where required, and recover the member debt separately.</div></div></main>
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-[#244332] bg-[#0b2113] p-5"><p className="text-[10px] uppercase tracking-[.16em] text-[#8fa79a] font-bold">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>}
