'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'

function BrandPanel() {
  return <section className="relative p-10 lg:p-14 border-b lg:border-b-0 lg:border-r border-gray-100 overflow-hidden">
    <Link href="/" className="flex items-center gap-1 relative z-10 w-fit"><span className="text-[22px] font-extrabold tracking-tight text-gray-900">Alajo</span><svg width="18" height="18" viewBox="0 0 20 20" className="mt-1"><circle cx="10" cy="10" r="8" fill="none" stroke="#e5e7eb" strokeWidth="2.5"/><path d="M10 2 A8 8 0 0 1 17 8" fill="none" stroke="#eab308" strokeWidth="2.5" strokeLinecap="round"/><path d="M17 8 A8 8 0 0 1 14.5 16" fill="none" stroke="#16a34a" strokeWidth="2.5" strokeLinecap="round"/></svg></Link>
    <h1 className="relative z-10 mt-8 font-bold text-[28px] leading-[1.2] text-gray-900 max-w-[320px]">Smart Rotational Savings for <span className="text-[#16a34a]">Everyone</span></h1><p className="relative z-10 mt-3 text-[15px] text-gray-500 max-w-[300px]">Join thousands of people already saving and growing together with Alajo.</p>
    <div className="relative z-10 mt-8 space-y-5">{[['👥','Join Savings Groups','Become a member of a savings group that fits your goals.'],['💳','Make Contributions','Contribute monthly and track your savings progress.'],['💰','Receive Payouts','Get your payout based on your selected position in the group.']].map(([icon,title,text])=><div className="flex gap-3" key={title}><div className="w-9 h-9 shrink-0 rounded-full bg-green-50 flex items-center justify-center text-[#16a34a]">{icon}</div><div><p className="font-semibold text-[14px] text-gray-900">{title}</p><p className="text-[13px] text-gray-500">{text}</p></div></div>)}</div>
    <div className="absolute left-[-40px] bottom-[-40px] w-56 h-56 rounded-full bg-[#eab308]/25"/><div className="absolute left-[-60px] bottom-[-80px] w-64 h-64 rounded-full bg-[#14532d]/90"/>
  </section>
}

function MobileWelcome({ onLogin }: { onLogin: () => void }) {
  return <section className="lg:hidden relative min-h-[100svh] overflow-hidden bg-[#0b2313] text-white flex flex-col items-center px-6 pt-[max(24px,env(safe-area-inset-top))] pb-[max(24px,env(safe-area-inset-bottom))]">
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_38%,rgba(22,163,74,.28),transparent_42%),linear-gradient(160deg,#123524_0%,#0b2313_58%,#071a0e_100%)]"/><div className="absolute -right-32 top-[58%] w-[155%] h-44 rotate-[-14deg] rounded-[50%] border border-[#16a34a]/20"/><div className="absolute -right-40 top-[66%] w-[155%] h-52 rotate-[-14deg] rounded-[50%] border border-[#16a34a]/10"/>
    <div className="relative z-10 flex-1 w-full max-w-[390px] flex flex-col items-center justify-center text-center"><div className="relative w-[156px] h-[156px] flex items-center justify-center"><div className="absolute inset-0 rounded-full bg-[#16a34a]/15 blur-2xl"/><img src="/icons/alajo-mark.svg" alt="Alajo" className="relative w-[138px] h-[138px] drop-shadow-[0_10px_24px_rgba(234,179,8,.18)]"/></div><div className="mt-3 text-[40px] leading-none font-semibold tracking-[.17em] text-[#f5c542]">ALAJO</div><div className="mt-6 w-32 h-px bg-gradient-to-r from-transparent via-[#eab308] to-transparent relative"><span className="absolute left-1/2 -translate-x-1/2 -top-1 w-2 h-2 rounded-full bg-[#f5c542] shadow-[0_0_14px_4px_rgba(245,197,66,.45)]"/></div><p className="mt-5 text-[17px] font-light tracking-wide text-white/90">Smart Rotational Savings</p><button type="button" onClick={onLogin} className="mt-9 w-full max-w-[330px] h-[54px] rounded-xl bg-[#16a34a] text-white text-[17px] font-semibold shadow-[0_10px_28px_rgba(22,163,74,.25)] active:scale-[.99] transition hover:bg-[#15803d]">Login</button><p className="mt-4 text-center text-[14px] text-white/70">New to Alajo? <Link href="/signup" className="text-[#f5c542] font-medium">Create an account</Link></p></div>
  </section>
}

export default function LoginPage() {
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [remember,setRemember]=useState(true);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [show,setShow]=useState(false);const [mobileLogin,setMobileLogin]=useState(false)
  async function submit(e:FormEvent){e.preventDefault();setError('');setLoading(true);try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,remember})});const data=await response.json();if(!response.ok){setError(data.error||'Unable to log in. Please try again.');return}window.location.assign('/dashboard')}catch{setError('Unable to log in right now. Please try again.')}finally{setLoading(false)}}
  function google(){setError('Google sign-in is not available yet. Please use your email and password.')}
  return <main className="min-h-screen bg-white grid lg:grid-cols-2">
    <MobileWelcome onLogin={()=>setMobileLogin(true)}/>
    <div className={`lg:hidden ${mobileLogin?'block':'hidden'} min-h-[100svh] bg-[#f7f8f9] px-5 pt-[max(32px,env(safe-area-inset-top))] pb-10`}>
      <div className="mx-auto max-w-[390px] pt-8"><div className="flex flex-col items-center text-center"><img src="/icons/alajo-mark.svg" alt="Alajo" className="w-14 h-14"/><p className="mt-2 font-bold tracking-[.16em] text-[#14532d]">ALAJO</p><h2 className="font-extrabold text-[27px] text-gray-900 mt-7">Welcome Back</h2><p className="mt-1 text-gray-500 text-[15px]">Sign in to your Alajo account</p></div>
      <form onSubmit={submit} className="mt-8 space-y-5"><div><label htmlFor="mobile-email" className="block text-[14px] font-semibold text-gray-900 mb-1.5">Email Address</label><div className="flex items-center gap-2 border border-gray-200 rounded-xl px-3 py-3 bg-white"><span className="text-gray-400">✉️</span><input id="mobile-email" required autoComplete="email" type="email" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)} className="w-full outline-none text-[14px] text-gray-800 bg-transparent"/></div></div><div><label htmlFor="mobile-password" className="block text-[14px] font-semibold text-gray-900 mb-1.5">Password</label><div className="flex items-center gap-2 border border-gray-200 rounded-xl px-3 py-3 bg-white"><span className="text-gray-400">🔒</span><input id="mobile-password" required autoComplete="current-password" type={show?'text':'password'} placeholder="Enter your password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full outline-none text-[14px] text-gray-800 bg-transparent"/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)} className="text-gray-400">{show?'◉':'◌'}</button></div></div><div className="flex items-center justify-between text-[14px]"><label className="flex items-center gap-2 text-gray-700"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)} className="w-4 h-4 accent-[#16a34a]"/> Remember me</label><Link href="/forgot-password" className="text-[#16a34a] font-medium">Forgot Password?</Link></div>{error&&<p role="alert" className="text-sm text-red-600 bg-red-50 rounded-xl p-3">{error}</p>}<button type="submit" disabled={loading} className="block text-center w-full py-3.5 rounded-xl bg-[#14532d] text-white font-semibold text-[15px] disabled:opacity-60">{loading?'Signing in…':'Login to Alajo'}</button><div className="flex items-center gap-3 text-gray-300 text-[13px]"><div className="flex-1 h-px bg-gray-200"/>or<div className="flex-1 h-px bg-gray-200"/></div><button type="button" onClick={google} className="flex items-center justify-center gap-2 w-full py-3.5 rounded-xl border border-gray-200 bg-white font-semibold text-[15px] text-gray-800">Continue with Google</button><p className="text-center text-[14px] text-gray-500">Don't have an account? <Link href="/signup" className="text-[#16a34a] font-semibold">Create an account</Link></p><p className="text-center text-[11px] text-gray-400 leading-5">Your account is protected with secure authentication.</p></form></div>
    </div>
    <div className="hidden lg:block lg:contents"><BrandPanel/><section className="p-10 lg:p-14 flex flex-col justify-center"><div className="max-w-[380px] w-full mx-auto"><h2 className="font-extrabold text-[26px] text-gray-900 text-center">Welcome Back 👋</h2><p className="mt-1 text-center text-gray-500 text-[15px]">Login to your account</p><form onSubmit={submit} className="mt-8 space-y-5"><div><label className="block text-[14px] font-semibold text-gray-900 mb-1.5">Email Address</label><div className="flex items-center gap-2 border border-gray-200 rounded-md px-3 py-2.5"><span className="text-gray-400">✉️</span><input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full outline-none text-[14px] text-gray-800"/></div></div><div><label className="block text-[14px] font-semibold text-gray-900 mb-1.5">Password</label><div className="flex items-center gap-2 border border-gray-200 rounded-md px-3 py-2.5"><span className="text-gray-400">🔒</span><input required type={show?'text':'password'} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full outline-none text-[14px] text-gray-800"/><button type="button" onClick={()=>setShow(!show)} className="text-gray-400">{show?'◉':'◌'}</button></div></div><div className="flex items-center justify-between text-[14px]"><label className="flex items-center gap-2 text-gray-700"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)} className="w-4 h-4 accent-[#16a34a]"/> Remember me</label><Link href="/forgot-password" className="text-[#16a34a] font-medium">Forgot Password?</Link></div>{error&&<p role="alert" className="text-sm text-red-600 bg-red-50 rounded-md p-3">{error}</p>}<button type="submit" disabled={loading} className="block text-center w-full py-3 rounded-md bg-[#14532d] text-white font-semibold text-[15px] disabled:opacity-60">{loading?'Signing in…':'Login'}</button><div className="flex items-center gap-3 text-gray-300 text-[13px]"><div className="flex-1 h-px bg-gray-200"/>or<div className="flex-1 h-px bg-gray-200"/></div><button type="button" onClick={google} className="flex items-center justify-center gap-2 w-full py-3 rounded-md border border-gray-200 font-semibold text-[15px] text-gray-800">Continue with Google</button><p className="text-center text-[14px] text-gray-500">Don't have an account? <Link href="/signup" className="text-[#16a34a] font-semibold">Create an account</Link></p></form></div></section></div>
  </main>
}
