'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export default function SignupPage() {
  const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [sent,setSent]=useState(false)
  async function submit(e:FormEvent){e.preventDefault();setError('');if(password!==confirm){setError('Passwords do not match');return}if(password.length<8){setError('Password must be at least 8 characters');return}setLoading(true);const supabase=createClient();const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:`${window.location.origin}/auth/callback`}});if(error)setError(error.message);else setSent(true);setLoading(false)}
  if(sent)return <main className="min-h-screen flex items-center justify-center p-6"><div className="max-w-md text-center"><div className="mx-auto w-16 h-16 rounded-full bg-green-50 flex items-center justify-center text-3xl">✉️</div><h1 className="mt-6 text-2xl font-extrabold">Verify Your Email</h1><p className="mt-3 text-gray-500">We've sent a verification link to <strong className="text-gray-900">{email}</strong>. Click the link to activate your account.</p><Link href="/login" className="inline-block mt-7 px-6 py-3 rounded-md bg-[#14532d] text-white font-semibold">Back to Login</Link></div></main>
  return <main className="min-h-screen flex items-center justify-center p-6 bg-white"><div className="w-full max-w-md"><Link href="/" className="font-extrabold text-2xl">Alajo</Link><h1 className="mt-10 text-2xl font-extrabold">Create your account</h1><p className="mt-1 text-gray-500">Start saving with Alajo.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-semibold">Full Name<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1.5 w-full border border-gray-200 rounded-md px-3 py-3 outline-none" /></label><label className="block text-sm font-semibold">Email Address<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1.5 w-full border border-gray-200 rounded-md px-3 py-3 outline-none" /></label><label className="block text-sm font-semibold">Password<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1.5 w-full border border-gray-200 rounded-md px-3 py-3 outline-none" /></label><label className="block text-sm font-semibold">Confirm Password<input required type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-1.5 w-full border border-gray-200 rounded-md px-3 py-3 outline-none" /></label>{error&&<p className="text-sm text-red-600 bg-red-50 p-3 rounded-md">{error}</p>}<button disabled={loading} className="w-full py-3 rounded-md bg-[#14532d] text-white font-semibold">{loading?'Creating account…':'Create Account'}</button><p className="text-center text-sm text-gray-500">Already have an account? <Link href="/login" className="text-[#16a34a] font-semibold">Login</Link></p></form></div></main>
}
