'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'

export default function CreatePrivateGroupPage(){
 const router=useRouter(); const [form,setForm]=useState({name:'',description:'',contribution_amount:'',start_date:'',cycle:'six_month'}); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');try{const r=await fetch('/api/groups/create-request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,contribution_amount:Number(form.contribution_amount)})});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Unable to create group');router.push('/groups')}catch(e){setError(e instanceof Error?e.message:'Unable to create group')}finally{setLoading(false)}}
 return <main className="min-h-screen bg-gray-50 p-5 sm:p-8"><div className="max-w-2xl mx-auto"><Link href="/groups" className="text-sm font-semibold text-[#15803d]">← Back to Groups</Link><div className="mt-5 bg-white rounded-2xl border border-gray-100 p-6 sm:p-8"><h1 className="text-2xl font-extrabold text-[#173323]">Create a Private Savings Group</h1><p className="mt-2 text-sm text-gray-500">Create the group, share your private link with friends, and fill every slot. Admin approval is required before the group becomes live.</p><form onSubmit={submit} className="mt-7 space-y-5"><label className="block"><span className="text-sm font-semibold">Group name</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-2 w-full rounded-xl border border-gray-200 px-4 py-3"/></label><label className="block"><span className="text-sm font-semibold">Description</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="mt-2 w-full rounded-xl border border-gray-200 px-4 py-3 min-h-24"/></label><div className="grid sm:grid-cols-2 gap-4"><label className="block"><span className="text-sm font-semibold">Monthly contribution</span><input required type="number" min="1" value={form.contribution_amount} onChange={e=>setForm({...form,contribution_amount:e.target.value})} className="mt-2 w-full rounded-xl border border-gray-200 px-4 py-3" placeholder="100000"/></label><label className="block"><span className="text-sm font-semibold">First contribution month</span><input required type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})} className="mt-2 w-full rounded-xl border border-gray-200 px-4 py-3"/></label></div><label className="block"><span className="text-sm font-semibold">Cycle</span><select value={form.cycle} onChange={e=>setForm({...form,cycle:e.target.value})} className="mt-2 w-full rounded-xl border border-gray-200 px-4 py-3"><option value="six_month">6 months — 6 members</option><option value="ten_month">10 months — 10 members</option></select></label>{error&&<div className="rounded-xl bg-red-50 text-red-700 px-4 py-3 text-sm">{error}</div>}<div className="rounded-xl bg-[#f0faf3] border border-[#dceee2] p-4 text-sm text-[#166534]"><strong>How it works:</strong> Your group starts as Filling. Friends join through your private link. When all 6 or 10 slots are filled, the group waits for admin approval. Contributions and payouts do not start before approval.</div><button disabled={loading} className="w-full rounded-xl bg-[#0f5b32] text-white py-3.5 font-bold disabled:opacity-50">{loading?'Creating…':'Create Private Group'}</button></form></div></div></main>
}
