'use client'
import { useEffect,useState } from 'react'
import { useParams,useRouter } from 'next/navigation'
export default function GroupInvitePage(){
 const {token}=useParams<{token:string}>(); const router=useRouter(); const [group,setGroup]=useState<any>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [joining,setJoining]=useState(false)
 useEffect(()=>{fetch(`/api/groups/invite/${token}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error||'This private group link is unavailable.');setGroup(d.group)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[token])
 async function join(){setJoining(true);setError('');try{const r=await fetch(`/api/groups/invite/${token}`,{method:'POST'});const d=await r.json();if(r.status===401){router.push('/login?redirect='+encodeURIComponent('/group-invite/'+token));return}if(!r.ok)throw new Error(d?.error||'Unable to join this group.');router.push('/groups')}catch(e){setError(e instanceof Error?e.message:'Unable to join this group.')}finally{setJoining(false)}}
 if(loading)return <main className="min-h-screen bg-gray-50 flex items-center justify-center"><p>Loading private group…</p></main>
 return <main className="min-h-screen bg-gray-50 flex items-center justify-center p-5"><section className="w-full max-w-lg bg-white rounded-2xl border border-gray-100 p-7"><p className="text-xs font-bold tracking-wider text-[#15803d]">ZEEPAY PRIVATE GROUP</p><h1 className="text-2xl font-extrabold text-[#173323] mt-2">{group?.name||'Private Savings Group'}</h1>{error?<div className="mt-5 rounded-xl bg-red-50 text-red-700 p-4 text-sm">{error}</div>:group&&<><p className="mt-2 text-sm text-gray-500">{group.description||'You have been invited to join this private savings group.'}</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-gray-50 p-4"><span className="text-xs text-gray-500">Contribution</span><strong className="block mt-1">₦{Number(group.contribution_amount).toLocaleString()}</strong></div><div className="rounded-xl bg-gray-50 p-4"><span className="text-xs text-gray-500">Cycle</span><strong className="block mt-1">{group.cycle==='ten_month'?'10 months':'6 months'}</strong></div></div><div className="mt-5 rounded-xl bg-[#f0faf3] border border-[#dceee2] p-4 text-sm text-[#166534]"><strong>{group.status==='full'?'Group is full — awaiting admin approval.':'Group is filling.'}</strong><br/>Contributions and payouts do not begin until all slots are filled and ZeePay admin approves the group.</div><button onClick={join} disabled={joining||group.status==='full'} className="mt-6 w-full rounded-xl bg-[#0f5b32] text-white py-3.5 font-bold disabled:opacity-50">{joining?'Joining…':group.status==='full'?'Group Full':'Join Private Group'}</button></>}</section></main>
}