'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { AlajoIcon } from '@/components/ui/alajo-icon'
import { UserPageShell } from '@/components/layout/user-page-shell'

type Group = { id: string; name: string; description: string | null; cycle: 'six_month' | 'ten_month'; contribution_amount: number; slot_count: number; start_date: string | null; status: string; memberCount: number }
type Membership = { id: string; group_id: string; status: string; joined_at: string; slot_id: string }
const money=(value:number)=>`₦${Number(value).toLocaleString('en-NG',{minimumFractionDigits:0})}`
const cycleLabel=(cycle:Group['cycle'])=>cycle==='ten_month'?'10 Months':'6 Months'

export default function GroupsClient({groups,memberships,userEmail}:{groups:Group[];memberships:Membership[];userEmail:string}){
 const supabase=createClient();const[tab,setTab]=useState<'my'|'available'|'past'>('my');const[items]=useState(groups),[myMemberships]=useState(memberships)
 const activeMemberships=useMemo(()=>myMemberships.filter(m=>m.status==='active'||m.status==='pending'),[myMemberships]);const pastMemberships=useMemo(()=>myMemberships.filter(m=>['completed','cancelled','replaced'].includes(m.status)),[myMemberships]);const myGroupIds=new Set(activeMemberships.map(m=>m.group_id))
 const visibleGroups=tab==='my'?items.filter(g=>myGroupIds.has(g.id)):tab==='past'?items.filter(g=>pastMemberships.some(m=>m.group_id===g.id)):items.filter(g=>!myGroupIds.has(g.id))
 const stats=[['groups','My Active Groups',activeMemberships.length,"Groups you're part of"],['add','Groups Joined',myMemberships.length,'Total groups joined'],['crown','Total Contributions','₦0','Across all groups'],['payouts','Total Payouts','₦0','Total received']] as const
 return <UserPageShell eyebrow="Savings workspace" title="Savings Groups" description="Manage the groups you belong to and discover available cycles." userName={userEmail.split('@')[0]||'User'}>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{stats.map(([icon,title,value,subtitle],i)=><div key={title} className={`${i===0?'bg-[#0f5b32] text-white border-[#0f5b32]':'bg-white text-[#173323] border-[#e6ebe8]'} rounded-2xl border p-4 sm:p-5`}><div className={`w-9 h-9 rounded-xl flex items-center justify-center ${i===0?'bg-white/15 text-white':'bg-[#eaf7ef] text-[#15803d]'}`}><AlajoIcon name={icon} size={17}/></div><p className={`mt-3 text-[11px] font-semibold ${i===0?'text-white/65':'text-[#748178]'}`}>{title}</p><p className="text-[18px] sm:text-[20px] font-extrabold">{value}</p><p className={`text-[10px] mt-1 ${i===0?'text-white/55':'text-[#98a29d]'}`}>{subtitle}</p></div>)}</div>
  <div className="mt-5 bg-white rounded-2xl border border-[#e6ebe8] overflow-hidden"><div className="px-5 pt-4 border-b border-[#edf0ee] flex gap-6 overflow-x-auto">{([['my','My Groups'],['available','Available Groups'],['past','Past Groups']] as const).map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`pb-3 text-[12px] font-semibold whitespace-nowrap border-b-2 transition ${tab===key?'text-[#15803d] border-[#16a34a]':'text-[#8a9690] border-transparent hover:text-[#315342]'}`}>{label}</button>)}</div>
   <div className="p-4 sm:p-5 grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3">{visibleGroups.map(group=>{const joined=myGroupIds.has(group.id),payout=Number(group.contribution_amount)*group.slot_count,isFull=group.status==='full'||group.memberCount>=group.slot_count;return <article key={group.id} className="rounded-xl border border-[#e7ece9] p-4 hover:border-[#b9d8c4] hover:shadow-[0_8px_25px_rgba(15,91,50,.07)] transition"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h4 className="font-bold text-[#173323] text-[14px] truncate">{group.name}</h4><p className="text-[10px] text-[#8a9690] mt-1 line-clamp-2">{group.description||'Savings group'}</p></div><span className={`text-[9px] font-semibold px-2 py-1 rounded-full shrink-0 ${isFull?'bg-[#f0f2f1] text-[#758078]':'bg-[#eaf7ef] text-[#15803d]'}`}>{isFull?'Full':joined?'Active':'Open'}</span></div><div className="mt-3 grid grid-cols-2 gap-y-2 text-[11px]"><p><span className="text-[#8a9690]">Contribution</span><br/><b>{money(Number(group.contribution_amount))}</b></p><p><span className="text-[#8a9690]">Cycle</span><br/><b>{cycleLabel(group.cycle)}</b></p><p><span className="text-[#8a9690]">Members</span><br/><b>{group.memberCount}/{group.slot_count}</b></p><p><span className="text-[#8a9690]">Payout</span><br/><b>{money(payout)}</b></p></div>{joined?<div className="mt-3 rounded-lg bg-[#eaf7ef] text-[#15803d] px-3 py-2 text-[10px] font-semibold flex items-center gap-2"><AlajoIcon name="check" size={14}/>You are a member of this group.</div>:tab==='available'?<Link href={isFull?'#':`/join-group?group=${encodeURIComponent(group.id)}`} aria-disabled={isFull} className={`mt-3 flex items-center justify-center gap-2 w-full ${isFull?'pointer-events-none opacity-50 bg-[#dfe5e1] text-[#718078]':'bg-[#0f5b32] text-white hover:bg-[#0c4b29]'} font-semibold rounded-lg py-2.5 text-[11px] transition hover:-translate-y-0.5 active:scale-[.98]`}>Join Group <AlajoIcon name="arrow-up" size={14}/></Link>:null}</article>})}</div>
   {visibleGroups.length===0&&<div className="p-10 text-center border-t border-[#edf0ee]"><p className="font-semibold text-[#30463a] text-sm">{tab==='my'?'You have not joined a group yet.':tab==='past'?'No past groups yet.':'No available groups right now.'}</p><p className="text-[11px] text-[#8a9690] mt-1">Available groups will appear here automatically.</p>{tab==='my'&&<button onClick={()=>setTab('available')} className="mt-3 text-[#15803d] font-semibold text-[11px]">Browse Available Groups →</button>}</div>}
  </div>
 </UserPageShell>
}
