ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS country_code text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS market_id uuid;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='markets') THEN ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_market_id_fkey; ALTER TABLE public.profiles ADD CONSTRAINT profiles_market_id_fkey FOREIGN KEY (market_id) REFERENCES public.markets(id) ON DELETE SET NULL; END IF; END $$;
CREATE INDEX IF NOT EXISTS profiles_country_code_idx ON public.profiles(country_code);
CREATE OR REPLACE FUNCTION public.admin_payment_provider_config() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='public' AS $$
DECLARE r text; BEGIN SELECT public.get_my_admin_role()::text INTO r; IF r IS NULL THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF; RETURN jsonb_build_object('markets',(SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) FROM (SELECT m.id,m.country_code,m.country_name,m.currency_code,m.status,coalesce((SELECT jsonb_agg(jsonb_build_object('id',mpc.id,'provider_id',mpc.provider_id,'provider_code',pd.code,'provider_name',pd.name,'capability',mpc.capability,'is_active',mpc.is_active,'priority',mpc.priority) ORDER BY mpc.capability,mpc.priority) FROM public.market_provider_configs mpc JOIN public.provider_definitions pd ON pd.id=mpc.provider_id WHERE mpc.market_id=m.id),'[]'::jsonb) providers FROM public.markets m ORDER BY m.country_name) x)); END; $$;
CREATE OR REPLACE FUNCTION public.admin_set_market_provider(p_config_id uuid,p_active boolean) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='public' AS $$
DECLARE r text; BEGIN SELECT public.get_my_admin_role()::text INTO r; IF r IS NULL THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF; UPDATE public.market_provider_configs SET is_active=p_active,updated_at=now() WHERE id=p_config_id; IF NOT FOUND THEN RAISE EXCEPTION 'CONFIG_NOT_FOUND'; END IF; RETURN jsonb_build_object('id',p_config_id,'is_active',p_active); END; $$;
REVOKE ALL ON FUNCTION public.admin_payment_provider_config() FROM anon,public; GRANT EXECUTE ON FUNCTION public.admin_payment_provider_config() TO authenticated;
REVOKE ALL ON FUNCTION public.admin_set_market_provider(uuid,boolean) FROM anon,public; GRANT EXECUTE ON FUNCTION public.admin_set_market_provider(uuid,boolean) TO authenticated;
