'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'

const money=(v:number)=>`₦${Number(v||0).toLocaleString('en-NG',{minimumFractionDigits:2})}`
type Data={walletBalance:number;totalContributions:number;thisMonth:number;upcoming:number;completed:number}
const cards=[
 {key:'walletBalance',label:'Wallet Balance',sub:'Available Balance',tone:'green',icon:'◈'},
 {key:'totalContributions',label:'Total Contributions',sub:'Across all groups',tone:'blue',icon:'↘'},
 {key:'thisMonth',label:'This Month',sub:'August 2026',tone:'orange',icon:'◷'},
 {key:'upcoming',label:'Upcoming',sub:'Due in the next 7 days',tone:'indigo',icon:'↗'},
 {key:'completed',label:'Completed',sub:'Total completed',tone:'purple',icon:'✓'}
] as const

export default function DashboardPage(){
 const[name,setName]=useState('User')
 const[loading,setLoading]=useState(true)
 const[data,setData]=useState<Data>({walletBalance:0,totalContributions:0,thisMonth:0,upcoming:0,completed:0})
 const[animated,setAnimated]=useState<Data>({walletBalance:0,totalContributions:0,thisMonth:0,upcoming:0,completed:0})
 useEffect(()=>{Promise.all([fetch('/api/auth/session',{cache:'no-store'}),fetch('/api/dashboard',{cache:'no-store'})]).then(async([s,d])=>{if(s.status===401||d.status===401){window.location.replace('/login');return}const session=s.ok?await s.json():null;const dashboard=d.ok?await d.json():null;if(session?.name)setName(session.name);if(dashboard?.authenticated){const c=dashboard.contributions||{};setData({walletBalance:dashboard.wallet?.balance??0,totalContributions:c.total??0,thisMonth:c.thisMonth??0,upcoming:c.upcoming??0,completed:c.completed??0})}}).catch(()=>{}).finally(()=>setLoading(false))},[])
 useEffect(()=>{if(loading)return;const start=performance.now(),duration=900;const tick=(now:number)=>{const p=Math.min((now-start)/duration,1);const ease=1-Math.pow(1-p,3);setAnimated({walletBalance:data.walletBalance*ease,totalContributions:data.totalContributions*ease,thisMonth:data.thisMonth*ease,upcoming:data.upcoming*ease,completed:data.completed*ease});if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)},[data,loading])
 return <div className="min-h-screen bg-[#f6f8f7] text-gray-900 overflow-hidden">
 <style jsx global>{`@keyframes fadeUp{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:translateY(0)}}@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-4px)}}@keyframes pulseSoft{0%,100%{opacity:.55}50%{opacity:1}}.dashboard-card{animation:fadeUp .65s cubic-bezier(.22,1,.36,1) both;transition:transform .3s ease,box-shadow .3s ease,border-color .3s ease}.dashboard-card:hover{transform:translateY(-6px);box-shadow:0 18px 45px rgba(11,35,19,.10);border-color:rgba(22,163,74,.18)}.wallet-glow{box-shadow:0 18px 50px rgba(22,163,74,.14)}.icon-float{animation:float 3s ease-in-out infinite}.soft-pulse{animation:pulseSoft 2s ease-in-out infinite}`}</style>
 <aside className="hidden lg:flex w-[250px] min-h-screen bg-[#0b2313] text-white p-5 fixed inset-y-0 left-0 flex-col shadow-2xl shadow-black/10">
   <Link href="/dashboard" className="text-[26px] font-extrabold tracking-tight flex items-center gap-2">Alajo <span className="text-yellow-400 text-lg">✦</span></Link>
   <nav className="mt-9 flex-1 space-y-1 text-[14px]">{[['Dashboard','/dashboard'],['Groups','/groups'],['Contributions','/contributions'],['Payouts','/payouts'],['Wallet','/wallet'],['Transactions','/transactions'],['Invite & Earn','/invite-earn'],['Notifications','/notifications'],['Settings','/settings'],['Help Center','/help-center']].map(([label,href])=><Link key={label} href={href} className={`flex items-center px-3 py-2.5 rounded-xl transition ${label==='Dashboard'?'bg-white/10 text-white shadow-inner':'text-gray-300 hover:bg-white/5 hover:text-white'}`}><span className="w-6">{label==='Dashboard'?'⌂':label==='Groups'?'♧':label==='Contributions'?'▤':label==='Payouts'?'₦':label==='Wallet'?'◈':label==='Transactions'?'▥':label==='Invite & Earn'?'♢':label==='Notifications'?'♧':label==='Settings'?'⚙':'?'}</span>{label}</Link>)}</nav>
   <Link href="/login" className="flex items-center gap-2 text-gray-300 px-3 py-2.5 rounded-xl hover:bg-white/5">↩ Logout</Link>
 </aside>
 <main className="lg:ml-[250px]">
  <header className="h-[76px] bg-white/90 backdrop-blur border-b border-gray-100 px-5 sm:px-8 flex items-center justify-between sticky top-0 z-20"><div><p className="text-gray-400 text-[12px] uppercase tracking-[.16em] font-semibold">Overview</p><h1 className="font-display font-bold text-[21px] mt-0.5">Good morning, {name}</h1></div><div className="flex items-center gap-4"><div className="relative text-gray-500 text-xl">♧<span className="absolute -top-1 -right-2 w-2 h-2 rounded-full bg-yellow-400 soft-pulse"/></div><div className="w-9 h-9 rounded-full bg-gradient-to-br from-[#dcefe2] to-[#b8d8c2] flex items-center justify-center font-bold text-[#0b2313]">{name.charAt(0).toUpperCase()}</div></div></header>
  <section className="p-5 sm:p-8 max-w-[1320px]">
   <div className="relative overflow-hidden rounded-2xl bg-[#0b2313] text-white p-6 sm:p-7 mb-7 shadow-xl shadow-[#0b2313]/10"><div className="absolute -right-16 -top-20 w-64 h-64 rounded-full bg-green-400/10 blur-2xl"/><div className="absolute right-20 bottom-0 w-32 h-32 rounded-full bg-yellow-400/5 blur-xl"/><div className="relative flex items-end justify-between gap-6"><div><p className="text-green-200/80 text-[12px] uppercase tracking-[.18em] font-semibold">Your savings journey</p><h2 className="font-display text-[27px] sm:text-[30px] font-bold mt-2">Build your savings, one cycle at a time.</h2><p className="text-gray-300 text-[13px] mt-2 max-w-xl">Stay on top of contributions, wallet funds and upcoming payouts from one place.</p></div><Link href="/wallet" className="hidden sm:block shrink-0 bg-white text-[#0b2313] font-semibold text-[13px] px-4 py-2.5 rounded-xl hover:bg-green-50 transition">Manage Wallet →</Link></div></div>
   <div className="grid grid-cols-2 xl:grid-cols-5 gap-4 sm:gap-5">{cards.map((card,i)=>{const value=animated[card.key];const isWallet=card.key==='walletBalance';const styles={green:'bg-green-50 text-[#16a34a]',blue:'bg-blue-50 text-blue-500',orange:'bg-orange-50 text-orange-500',indigo:'bg-indigo-50 text-indigo-500',purple:'bg-purple-50 text-purple-500'} as Record<string,string>;return <div key={card.key} className={`dashboard-card bg-white rounded-2xl border border-gray-100 p-5 sm:p-6 relative overflow-hidden ${isWallet?'wallet-glow':''}`} style={{animationDelay:`${i*80}ms`}}><div className="absolute -right-8 -top-8 w-24 h-24 rounded-full bg-gray-50"/><div className="relative flex items-start justify-between"><div className={`w-11 h-11 rounded-2xl ${styles[card.tone]} flex items-center justify-center text-lg font-bold icon-float`}>{card.icon}</div>{isWallet&&<span className="text-[10px] uppercase tracking-wider font-bold text-[#16a34a] bg-green-50 px-2 py-1 rounded-full">Live</span>}</div><p className="mt-5 text-gray-500 text-[12px] font-medium">{card.label}</p><p className="text-[20px] sm:text-[22px] font-bold text-gray-900 mt-1 tracking-tight">{loading?'—':money(value)}</p><p className="text-[11px] text-gray-400 mt-1">{card.sub}</p>{isWallet&&<div className="mt-4 h-1.5 rounded-full bg-green-50 overflow-hidden"><div className="h-full rounded-full bg-[#16a34a] w-[62%]"/></div>}</div>})}</div>
   <div className="mt-7 grid grid-cols-1 xl:grid-cols-2 gap-5"><div className="bg-white rounded-2xl border border-gray-100 p-6 dashboard-card" style={{animationDelay:'500ms'}}><div className="flex justify-between items-center"><div><h2 className="font-semibold text-[16px]">Recent Activity</h2><p className="text-[12px] text-gray-400 mt-1">Your latest savings activity</p></div><Link href="/transactions" className="text-[#16a34a] text-[13px] font-semibold">View All →</Link></div><div className="mt-6 rounded-xl bg-gray-50 border border-dashed border-gray-200 p-6 text-center text-sm text-gray-400">Your recent savings activity will appear here.</div></div><div className="bg-white rounded-2xl border border-gray-100 p-6 dashboard-card" style={{animationDelay:'580ms'}}><div className="flex justify-between items-center"><div><h2 className="font-semibold text-[16px]">My Active Groups</h2><p className="text-[12px] text-gray-400 mt-1">Your current savings groups</p></div><Link href="/groups" className="text-[#16a34a] text-[13px] font-semibold">View All →</Link></div><div className="mt-6 rounded-xl bg-gray-50 border border-dashed border-gray-200 p-6 text-center text-sm text-gray-400">Open Groups to view your savings groups.</div></div></div>
  </section>
 </main></div>
}
